import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const workflow = readFileSync(
  new URL("../../../.github/workflows/ha-isolated-sequence-failback.yml", import.meta.url),
  "utf8",
);

test("HA06-B rehearsal is isolated and provider-secret free", () => {
  assert.match(workflow, /postgres:17/);
  assert.match(workflow, /two_disposable_postgresql_17_nodes/);
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /pull_request:/);
  assert.doesNotMatch(workflow, /\npush:/);
  assert.doesNotMatch(workflow, /SUPABASE_DATABASE_URL_DIRECT|NEON_DATABASE_URL_DIRECT/);
});

test("HA06-B creates a real identity-backed sequence divergence", () => {
  assert.match(workflow, /generated by default as identity primary key/);
  assert.match(workflow, /akarfinder_ha_sequence_canary_id_seq/);
  assert.match(workflow, /source_last" = "3"/);
  assert.match(workflow, /target_last" = "6"/);
  assert.match(workflow, /pre-repair sequence was unexpectedly safe/);
});

test("HA06-B preserves single-writer semantics through failback freeze", () => {
  assert.match(workflow, /ha_seq_writer/);
  assert.match(workflow, /Enter isolated FAILBACK_FREEZE/);
  assert.match(workflow, /app writer remained writable during FAILBACK_FREEZE/);
  assert.match(workflow, /target app writer became writable after source promotion/);
  assert.match(workflow, /both_writers_fenced_during_freeze: "PASS"/);
});

test("HA06-B reverse delta uses origin filtering and no baseline copy", () => {
  assert.match(workflow, /copy_data=false, origin=none/);
  assert.match(workflow, /reverse origin filter is not none/);
  assert.match(workflow, /reverse incident delta did not fully apply/);
});

test("HA06-B sequence repair honors is_called semantics", () => {
  assert.match(workflow, /select is_called from public\.akarfinder_ha_sequence_canary_id_seq/);
  assert.match(workflow, /unexpected source is_called semantics/);
  assert.match(workflow, /setval\('public\.akarfinder_ha_sequence_canary_id_seq'/);
  assert.match(workflow, /post-repair is_called must be true/);
  assert.match(workflow, /sequence collision risk remains after repair/);
  assert.match(workflow, /sequence_repair_with_is_called_semantics: "PASS"/);
});

test("HA06-B proves final parity before source promotion", () => {
  assert.match(workflow, /final row parity mismatch/);
  assert.match(workflow, /count\(distinct id\)/);
  assert.match(workflow, /string_agg\(id::text/);
  assert.match(workflow, /to_char\(updated_at at time zone 'UTC'/);
  assert.match(workflow, /final_row_parity: "PASS"/);
  assert.match(workflow, /conflicts: 0/);
  assert.match(workflow, /duplicates: 0/);
});

test("HA06-B proves first post-failback generated ID is collision-free", () => {
  assert.match(workflow, /returning id/);
  assert.match(workflow, /generated_id" = "7"/);
  assert.match(workflow, /first post-failback generated id was not collision-free/);
  assert.match(workflow, /first_post_failback_generated_id_collision_free: "PASS"/);
});

test("HA06-B measures isolated failback RTO in milliseconds", () => {
  assert.match(workflow, /FAILBACK_FREEZE_EPOCH_MS/);
  assert.match(workflow, /OBSERVED_FAILBACK_RTO_MS/);
  assert.match(workflow, /observed_failback_rto_ms/);
});

test("HA06-B artifact is traceable and secret guarded", () => {
  assert.match(workflow, /REHEARSAL_HEAD_SHA:/);
  assert.match(workflow, /github_execution_sha/);
  assert.match(workflow, /ISOLATED_SEQUENCE_FAILBACK_PASS/);
  assert.match(workflow, /Secret-like material detected in sequence failback artifact/);
  assert.match(workflow, /retention-days: 30/);
  assert.match(workflow, /provider_specific_certification: false/);
});

test("HA06-B cancels obsolete PR runs", () => {
  assert.match(workflow, /cancel-in-progress: true/);
  assert.match(workflow, /ha-isolated-sequence-failback-\$\{\{/);
});
