import { createClient } from "npm:@supabase/supabase-js@2";

type AssetSpec = { role:"signature"|"immobilier"|"lifestyle"; sourceUrl:string; storagePath:string; width:number; height:number; bytes:number; sha1:string; };
const BUCKET="neighborhood-visuals";
const COMMONS="https://commons.wikimedia.org/wiki/Special:Redirect/file/";
const ASSETS: readonly AssetSpec[] = [
  { role:"signature", sourceUrl:`${COMMONS}Rabat%20hay%20ryad.jpg`, storagePath:"rabat/hay-riad/signature/master.jpg", width:3251,height:4338,bytes:6_395_398,sha1:"f02d4795b4df3c7cd6608472b82f9fda1c5d4796" },
  { role:"immobilier", sourceUrl:`${COMMONS}Hay%20Riad%20%28335665610%29.jpg`, storagePath:"rabat/hay-riad/immobilier/master.jpg", width:3456,height:2304,bytes:4_353_803,sha1:"54c45f4914839a1a9ee3a65acf3d570f3450b653" },
  { role:"lifestyle", sourceUrl:`${COMMONS}Hay%20Riad%20%28335665617%29.jpg`, storagePath:"rabat/hay-riad/lifestyle/master.jpg", width:2800,height:1866,bytes:921_974,sha1:"a91237d667511ed212e9c46b343d96cff5054c5f" },
] as const;
function jpegDimensions(bytes:Uint8Array){ if(bytes.length<4||bytes[0]!==0xff||bytes[1]!==0xd8) throw new Error("source is not a JPEG"); let o=2; while(o+8<bytes.length){ if(bytes[o]!==0xff){o++;continue;} const m=bytes[o+1]; o+=2; if(m===0xd8||m===0xd9) continue; if(o+2>bytes.length) break; const l=(bytes[o]<<8)|bytes[o+1]; if(l<2||o+l>bytes.length) break; if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(m)) return {height:(bytes[o+3]<<8)|bytes[o+4],width:(bytes[o+5]<<8)|bytes[o+6]}; o+=l;} throw new Error("JPEG dimensions could not be decoded"); }
async function sha1Hex(bytes:Uint8Array){ const exact=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer; const digest=await crypto.subtle.digest("SHA-1",exact); return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join(""); }
Deno.serve(async(req:Request)=>{ if(req.method!=="POST") return new Response("POST required",{status:405}); const body=await req.json().catch(()=>null) as {lot?:string;confirmExactSources?:boolean}|null; if(body?.lot!=="P1.5-HAY-RIAD"||body.confirmExactSources!==true) return Response.json({error:"bounded P1.5 confirmation required"},{status:400});
 const url=Deno.env.get("SUPABASE_URL"); const raw=Deno.env.get("SUPABASE_SECRET_KEYS"); const legacy=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); const key=raw?JSON.parse(raw).default:legacy; if(!url||!key) return Response.json({error:"admin storage environment unavailable"},{status:500}); const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}); const results=[];
 for(const asset of ASSETS){ const response=await fetch(asset.sourceUrl,{headers:{"User-Agent":"AkarFinder-P1.5-Hay-Riad/1.0"},redirect:"follow"}); if(!response.ok) throw new Error(`${asset.role}: source fetch failed ${response.status}`); const bytes=new Uint8Array(await response.arrayBuffer()); const dims=jpegDimensions(bytes); if(dims.width!==asset.width||dims.height!==asset.height) throw new Error(`${asset.role}: dimension drift`); if(bytes.byteLength!==asset.bytes) throw new Error(`${asset.role}: byte-size drift ${bytes.byteLength}`); const sha1=await sha1Hex(bytes); if(sha1!==asset.sha1) throw new Error(`${asset.role}: SHA-1 mismatch ${sha1}`); const exact=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer; const {data,error}=await admin.storage.from(BUCKET).upload(asset.storagePath,new Blob([exact],{type:"image/jpeg"}),{contentType:"image/jpeg",cacheControl:"31536000",upsert:true}); if(error) throw new Error(`${asset.role}: storage upload failed: ${error.message}`); results.push({role:asset.role,path:data.path,width:dims.width,height:dims.height,bytes:bytes.byteLength,sha1}); }
 return Response.json({lot:"P1.5-HAY-RIAD",ingested:results.length,results}); });
