import fs from 'node:fs/promises';
import path from 'node:path';
import { classifyReservoirCandidate } from '../data-mass/reservoir-qualification';

const OUT=process.env.GAP_HUNT_OUT ?? '.tmp/historical-gap-hunt';
const PAGE=1000;
const TARGETS=new Set([
  'agenz.ma','1immo.ma','ma.afribaba.com','masaken.ma','soukimmobilier.com','mouldar.com',
  'promoimmomarrakech.com','logic-immo.com','yakeey.com','2p.ma','1000-annonces.com',
  'housing.place','expat.com','milkiya.ma','sakane.ma','domio.ma','dabaannonce.ma',
  'portail-immobilier.ma','souqcity.ma','kawtarimmobilier.com','atlasimmobilier.com'
]);
function env(n:string){const v=process.env[n];if(!v)throw new Error(`missing ${n}`);return v;}
const norm=(d:string)=>d.trim().toLowerCase().replace(/^www\./,'');
const canon=(raw:string)=>{try{const u=new URL(raw);u.hash='';u.hostname=u.hostname.toLowerCase().replace(/^www\./,'');if(u.pathname.length>1)u.pathname=u.pathname.replace(/\/+$/,'');return u.toString();}catch{return raw.trim();}};
async function rest<T>(table:string,params:Record<string,string>):Promise<T[]>{const u=new URL(`/rest/v1/${table}`,env('SUPABASE_URL'));for(const[k,v]of Object.entries(params))u.searchParams.set(k,v);const key=env('SUPABASE_SERVICE_ROLE_KEY');for(let a=1;a<=3;a++){const r=await fetch(u,{headers:{apikey:key,authorization:`Bearer ${key}`},signal:AbortSignal.timeout(60000)});if(r.ok)return r.json() as Promise<T[]>;const body=await r.text();if(a===3||!(r.status===429||r.status>=500))throw new Error(`${table} ${r.status} ${body}`);await new Promise(res=>setTimeout(res,500*a));}return[];}
type D={id:string,source_domain:string,source_url:string,canonical_url:string|null,title:string|null,snippet:string|null,discovery_query:string|null,content_fingerprint:string|null,last_seen_at:string|null};
type S={canonical_url:string,source_domain?:string|null};
async function readDiscovery(){const out:D[]=[];let last='';for(;;){const q:Record<string,string>={select:'id,source_domain,source_url,canonical_url,title,snippet,discovery_query,content_fingerprint,last_seen_at',order:'id.asc',limit:String(PAGE)};if(last)q.id=`gt.${last}`;const p=await rest<D>('discovery_candidates',q);out.push(...p.filter(x=>TARGETS.has(norm(x.source_domain))));if(p.length<PAGE)break;const n=p.at(-1)?.id;if(!n||n===last)throw new Error('keyset stalled');last=n;}return out;}
async function readSeeds(){const out:S[]=[];for(let offset=0;;offset+=PAGE){const p=await rest<S>('source_offer_seeds',{select:'canonical_url,source_domain',order:'canonical_url.asc',limit:String(PAGE),offset:String(offset)});out.push(...p);if(p.length<PAGE)break;}return out;}
async function main(){const [rows,seeds]=await Promise.all([readDiscovery(),readSeeds()]);const seedSet=new Set(seeds.map(x=>canon(x.canonical_url)));const uniq=new Map<string,D>();for(const r of rows){const raw=r.canonical_url||r.source_url;if(!raw)continue;const u=canon(raw);const e=uniq.get(u);if(!e||(r.last_seen_at??'')>(e.last_seen_at??''))uniq.set(u,r);}const by=new Map<string,{all:Set<string>,details:Set<string>,overlap:Set<string>,net:Set<string>}>();for(const [url,r] of uniq){const d=norm(r.source_domain);if(!TARGETS.has(d))continue;const b=by.get(d)??{all:new Set(),details:new Set(),overlap:new Set(),net:new Set()};b.all.add(url);const c=classifyReservoirCandidate({sourceDomain:d,url,title:r.title,snippet:r.snippet,discoveryQuery:r.discovery_query,contentFingerprint:r.content_fingerprint});if(c.likelyRealEstate&&c.pageKind==='LIKELY_LISTING_DETAIL'&&c.geographyScope==='MOROCCO_LIKELY'){b.details.add(url);if(seedSet.has(url))b.overlap.add(url);else b.net.add(url);}by.set(d,b);}const domains=[...by.entries()].map(([sourceDomain,b])=>({sourceDomain,discoveryDistinct:b.all.size,detailDistinct:b.details.size,exactOverlapSeeds:b.overlap.size,exactNetNewVsSeeds:b.net.size})).sort((a,b)=>b.exactNetNewVsSeeds-a.exactNetNewVsSeeds);const summary={generatedAt:new Date().toISOString(),readOnly:true,databaseWrites:0,sourceNetworkRequests:0,detailPageFetches:0,targets:[...TARGETS],domains,totalExactNetNewVsSeeds:domains.reduce((s,x)=>s+x.exactNetNewVsSeeds,0)};await fs.mkdir(OUT,{recursive:true});await fs.writeFile(path.join(OUT,'summary.json'),JSON.stringify(summary,null,2)+'\n');await fs.writeFile(path.join(OUT,'domains.csv'),['source_domain,discovery_distinct,detail_distinct,exact_overlap_seeds,exact_net_new_vs_seeds',...domains.map(x=>`${x.sourceDomain},${x.discoveryDistinct},${x.detailDistinct},${x.exactOverlapSeeds},${x.exactNetNewVsSeeds}`)].join('\n')+'\n');console.log(JSON.stringify(summary,null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
