import type { PropertyVisualType } from "@/components/demo/PropertyVisual";

// Premium partner-page demo data. All entries are fictional, local-only and
// non-contractual. No real partner, phone number, URL, lead or inventory.
// DEMO-PROMOTER-AGENCY-REALISTIC-MOCKUP-1 — the data reads like a real
// partner page (realistic commercial mockup), while every figure stays
// clearly indicative and every entity fictional.

export const DEMO_PARTNER_PROMOTER_EXPERIENCE = {
  promoterName: "Atlas Résidences",
  monogram: "AR",
  tagline: "Des résidences familiales et haut standing, pensées pour la vie de quartier.",
  positioning: "Promoteur résidentiel premium — exemple fictif de présentation partenaire.",
  zones: ["Casablanca", "Dar Bouazza", "Bouskoura"],
  specialties: ["Résidences familiales", "Haut standing", "Plans 2D disponibles", "Livraisons par tranches"],
  badges: ["Page partenaire démo", "Plans 2D disponibles", "Présentation enrichie"],
  mainProject: "Résidence Les Jardins d'Anfa",
  projects: [
    {
      name: "Résidence Les Jardins d'Anfa",
      city: "Casablanca",
      district: "Anfa / Casablanca Finance City",
      type: "Familial premium",
      typologies: "2 chambres · 3 chambres · 4 pièces familial",
      surfaces: "72 – 128 m²",
      price: "À partir de 1 250 000 MAD — fourchette indicative",
      delivery: "Livraison indicative : tranche 1 fin 2027",
      status: "Tranche 1 en commercialisation",
      infoLevel: "Présentation enrichie — plans 2D disponibles",
      visual: "project-garden" as PropertyVisualType,
    },
    {
      name: "Rivage Dar Bouazza",
      city: "Dar Bouazza",
      district: "Front de mer résidentiel",
      type: "Résidentiel balnéaire",
      typologies: "Appartements terrasse · duplex · villas compactes",
      surfaces: "68 – 210 m²",
      price: "À partir de 980 000 MAD — fourchette indicative",
      delivery: "Livraison indicative : 2028",
      status: "Lancement prochain",
      infoLevel: "Présentation enrichie — plans 2D sur demande",
      visual: "residence-walkway" as PropertyVisualType,
    },
  ],
};

export const DEMO_PARTNER_PROJECT = {
  name: "Résidence Les Jardins d'Anfa",
  city: "Casablanca",
  district: "Anfa / Casablanca Finance City",
  locationLevel: "Zone approximative fictive à titre d'illustration",
  type: "Résidence familiale premium",
  priceRange: "Fourchette indicative fictive : 1 250 000 - 2 450 000 MAD",
  visuals: ["project-garden", "residence-walkway", "apartment-modern"] as PropertyVisualType[],
  phases: [
    { name: "Tranche 1", status: "En commercialisation (démo)", delivery: "Livraison indicative : T4 2027", note: "Premier ensemble d'unités présenté en démonstration." },
    { name: "Tranche 2", status: "Ouverture prochaine (démo)", delivery: "Livraison indicative : T2 2028", note: "Ouverture indicative selon validation partenaire." },
    { name: "Tranche 3", status: "Phase future (démo)", delivery: "Calendrier indicatif à confirmer", note: "Phase illustrée pour montrer la lecture long terme du projet." },
  ],
  typologies: [
    { name: "2 chambres 72 m²", surface: "72 m²", bedrooms: "2 chambres", bathrooms: "1 SDB", orientation: "Sud-Est indicative", parking: "Parking en option", terrace: "Balcon", price: "1,25M - 1,45M MAD indicatif", availability: "Disponible (démo)" },
    { name: "3 chambres 96 m²", surface: "96 m²", bedrooms: "3 chambres", bathrooms: "2 SDB", orientation: "Ouest indicative", parking: "1 place incluse", terrace: "Terrasse", price: "1,65M - 1,95M MAD indicatif", availability: "Sélection (démo)" },
    { name: "4 pièces familial 128 m²", surface: "128 m²", bedrooms: "3 chambres", bathrooms: "2 SDB", orientation: "Sud indicative", parking: "1 place incluse", terrace: "Grande terrasse", price: "2,05M - 2,30M MAD indicatif", availability: "Quantité limitée (démo)" },
    { name: "Duplex 165 m²", surface: "165 m²", bedrooms: "4 chambres", bathrooms: "3 SDB", orientation: "Double orientation indicative", parking: "2 places", terrace: "Terrasse familiale", price: "2,30M - 2,45M MAD indicatif", availability: "Sur demande (démo)" },
  ],
  floorPlans: [
    { title: "Plan 2 chambres 72 m²", surface: "72 m²", rooms: "Séjour + 2 chambres", orientation: "Sud-Est indicative", scope: "Unité type" },
    { title: "Plan 3 chambres 96 m²", surface: "96 m²", rooms: "Séjour + 3 chambres", orientation: "Ouest indicative", scope: "Unité type" },
    { title: "Plan 4 pièces 128 m²", surface: "128 m²", rooms: "Séjour + 3 chambres", orientation: "Sud indicative", scope: "Unité type" },
    { title: "Plan Duplex 165 m²", surface: "165 m²", rooms: "Double niveau", orientation: "Double orientation", scope: "Unité type" },
  ],
  modelApartment: {
    title: "Appartement témoin — 3 chambres — 96 m²",
    composition: ["Séjour lumineux", "Suite parentale", "2 chambres enfants", "Cuisine équipée", "Terrasse", "2 SDB"],
    strengths: ["Distribution lisible", "Espace familial", "Terrasse exploitable", "Plan 2D disponible"],
    pointsToVerify: ["Surface contractuelle", "Orientation exacte", "Charges", "Parking", "Cahier des charges"],
    visual: "appartement-familial" as PropertyVisualType,
    gallery: [
      "/demo/interiors/appartement-temoin-salon.png",
      "/demo/properties/villa-harhoura-exterior.png",
      "/demo/properties/gallery/apartment-modern-salon.jpg",
    ],
    specs: [
      "96 m²",
      "3 chambres",
      "2 SDB",
      "Terrasse",
      "1 place parking",
      "Orientation Ouest indicative",
      "Plan 2D disponible",
    ],
  },
  nearby: [
    { category: "Commerces", items: ["Dans le secteur — indicatif", "À confirmer sur place"] },
    { category: "Écoles et crèches", items: ["Dans l'environnement élargi — indicatif", "À confirmer auprès du partenaire"] },
    { category: "Santé", items: ["Clinique dans le secteur — indicatif", "Pharmacie à proximité — indicatif"] },
    { category: "Transport", items: ["Axes routiers proches — indicatif", "Taxi dans le secteur — indicatif"] },
    { category: "Loisirs", items: ["Espaces verts dans le secteur — indicatif"] },
  ],
  mobility: [
    "Voiture : accès aux grands axes à confirmer",
    "Transport : desserte à vérifier selon adresse finale",
    "Taxi : disponibilité indicative dans le secteur",
    "Marche : services proches à confirmer",
    "Stationnement : selon lot et contrat partenaire",
  ],
  neighborhood: {
    advantages: ["Secteur résidentiel recherché", "Projet adapté aux familles", "Services dans le secteur"],
    checks: ["Circulation", "Bruit selon rue", "Stationnement visiteurs", "Livraison effective", "Charges"],
  },
  reservationChecklist: [
    "Titre et autorisations",
    "Cahier des charges",
    "Plan signé",
    "Surface contractuelle",
    "Charges",
    "Livraison",
    "Frais annexes",
    "Syndic",
    "Parking",
    "Conditions de réservation",
  ],
};

export const DEMO_PARTNER_AGENCY_EXPERIENCE = {
  agencyName: "Rabat Select Immobilier",
  monogram: "RS",
  tagline: "Spécialiste Rabat & Harhoura — villas et appartements familiaux, achat et location longue durée.",
  positioning: "Agence partenaire fictive — exemple de présentation AkarFinder.",
  zones: ["Agdal", "Hay Riad", "Souissi", "Harhoura", "Hassan"],
  specialties: ["Achat familial", "Location longue durée", "Villas & appartements", "Accompagnement MRE", "Cadres en mobilité"],
  badges: ["Agence partenaire démo", "Fiches structurées", "Demande qualifiée"],
  advisor: {
    name: "Conseillère Sélection (fictif)",
    role: "Accompagnement acheteur et vendeur",
    note: "Dans une version partenaire, le contact s'affiche uniquement si l'agence l'autorise.",
  },
  method: [
    { step: "01", title: "Écoute du besoin", body: "Budget, quartiers cibles, horizon et points non négociables." },
    { step: "02", title: "Sélection structurée", body: "Fiches complètes : surface, étage, charges, points à confirmer." },
    { step: "03", title: "Visites et décision", body: "Visites organisées, lecture quartier et accompagnement jusqu'à l'accord." },
  ],
  listings: [
    {
      title: "Appartement familial 3 chambres",
      city: "Rabat",
      neighborhood: "Agdal",
      propertyType: "Appartement",
      transaction: "Achat",
      price: "2 150 000 MAD — indicatif",
      surface: "112 m²",
      bedrooms: "3 chambres",
      features: ["Étage 3", "Ascenseur", "Parking", "Terrasse"],
      locationLevel: "Quartier : Agdal — niveau 1 (démo)",
      contactMode: "Contact autorisé (fictif)",
      infoLevel: "Fiche structurée — informations complètes",
      visual: "appartement-familial" as PropertyVisualType,
      pointsToVerify: ["Charges", "Parking en titre", "État copropriété"],
    },
    {
      title: "Villa contemporaine avec jardin",
      city: "Harhoura",
      neighborhood: "Harhoura plage",
      propertyType: "Villa",
      transaction: "Achat",
      price: "5,2M – 5,8M MAD — fourchette indicative",
      surface: "280 m²",
      bedrooms: "4 chambres",
      features: ["Jardin", "Parking 2 voitures", "Double séjour"],
      locationLevel: "Zone approximative — niveau 2 (démo)",
      contactMode: "Contact autorisé (fictif)",
      infoLevel: "Fiche structurée — plan 2D recommandé",
      visual: "villa-premium" as PropertyVisualType,
      pointsToVerify: ["Titre foncier", "Travaux récents", "Clôture et jardin"],
    },
    {
      title: "Appartement location longue durée",
      city: "Rabat",
      neighborhood: "Hay Riad",
      propertyType: "Appartement",
      transaction: "Location",
      price: "9 500 MAD/mois — loyer indicatif",
      surface: "86 m²",
      bedrooms: "2 chambres",
      features: ["Résidence calme", "Cuisine équipée", "Gardiennage"],
      locationLevel: "Quartier : Hay Riad — niveau 1 (démo)",
      contactMode: "Contact autorisé (fictif)",
      infoLevel: "Fiche structurée — informations complètes",
      visual: "apartment-modern" as PropertyVisualType,
      pointsToVerify: ["Bail et préavis", "Charges mensuelles", "État des lieux"],
    },
  ],
  qualifiedRequests: [
    { profile: "Famille avec enfants", budget: "Budget indicatif : 1,8M - 2,2M MAD", zone: "Agdal ou Hay Riad", urgency: "Horizon : 3 mois (démo)", propertyType: "Appartement 3 chambres", importantPoint: "Écoles et parking", source: "Source de la demande : parcours Acheter (démo)" },
    { profile: "MRE", budget: "Budget indicatif : 4,5M - 6M MAD", zone: "Harhoura", urgency: "Voyage prévu cet été (démo)", propertyType: "Villa familiale", importantPoint: "Gestion à distance", source: "Source de la demande : profil MRE (démo)" },
    { profile: "Cadre en mobilité", budget: "Budget indicatif : 8 000 - 11 000 MAD/mois", zone: "Hay Riad", urgency: "À emménager sous 30 jours (démo)", propertyType: "Appartement 2 chambres", importantPoint: "Résidence calme et proximité bureaux", source: "Source de la demande : parcours Louer (démo)" },
  ],
};
