// OPENSERP-SERVERLESS-STATE-PERSISTENCE-1 -- seed generation (post-Gate-B
// reconciliation order, steps 1-3).
//
// Generates a deterministic, additive, idempotent SQL seed (and a JSON
// manifest describing it) for the two new state tables, directly from the
// static, immutable data/openserp/query-universe-v1.json catalog. Reuses
// hashQueryDefinition() from serverless-state-service.ts and the budget
// constants from budget-policy.ts so this script can never compute a
// different definition hash or default budget than the runtime code does.
//
// Determinism: no wall-clock timestamp is embedded anywhere in the generated
// SQL text -- created_at/updated_at are left unspecified so the tables' own
// `default now()` applies at apply-time, not at generation-time. Given the
// same committed query-universe-v1.json, running this script twice must
// produce byte-identical .sql/.json files (verified by the caller diffing
// their SHA-256 hashes).
//
// Idempotent: both INSERT statements use ON CONFLICT ... DO NOTHING, so
// re-applying this seed against a database that already has rotation
// history or budget state never overwrites it -- only fills gaps for
// query_ids not yet present (matches seedMissingQueryStates' own
// ignoreDuplicates behavior). No DELETE, no UPDATE, no listing table is
// touched. No URL, snippet, or PII is included (only query_id, city,
// district, tier, transaction, property_type, language, engine, hash).

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { hashQueryDefinition, type StaticQueryDefinition } from "../../lib/openserp-ingestion/state/serverless-state-service";
import { MIN_BUDGET, MAX_BUDGET, START_BUDGET } from "../../lib/openserp-ingestion/budget-policy";
import type { OpenSerpEngineName } from "../../lib/openserp-ingestion/state/query-rotation-state-repository";

const UNIVERSE_PATH = join(process.cwd(), "data/openserp/query-universe-v1.json");
const OUT_SQL_PATH = join(process.cwd(), "data/audits/openserp-serverless-state-seed.sql");
const OUT_MANIFEST_PATH = join(process.cwd(), "data/audits/openserp-serverless-state-seed.json");

const ENGINE_STATE_VERSION = "openserp-engine-budget-state-v1";
const KNOWN_ENGINES: OpenSerpEngineName[] = ["bing", "duckduckgo", "ecosia"];

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function main() {
  const universe = JSON.parse(readFileSync(UNIVERSE_PATH, "utf8")) as {
    universe_version: string;
    queries: StaticQueryDefinition[];
  };

  const rotationRows = universe.queries
    .map((q) => {
      const hash = hashQueryDefinition(q);
      return `  (${sqlString(q.query_id)}, ${sqlString(universe.universe_version)}, ${sqlString(hash)}, null, null, 0, 0, 0, null, null)`;
    })
    .join(",\n");

  const budgetRows = KNOWN_ENGINES.map(
    (engine) =>
      `  (${sqlString(engine)}, ${sqlString(ENGINE_STATE_VERSION)}, ${START_BUDGET}, 0, 0, 0, 0, null, null, null, null)`,
  ).join(",\n");

  const sql = `-- OPENSERP-SERVERLESS-STATE-PERSISTENCE-1 -- deterministic seed.
-- Generated by scripts/openserp/generate-serverless-state-seed.ts from the
-- static data/openserp/query-universe-v1.json catalog (universe_version:
-- ${universe.universe_version}). Additive, idempotent (ON CONFLICT DO
-- NOTHING), transactional, no deletion, no listing table touched, no URL/
-- snippet/PII. created_at/updated_at intentionally omitted -- the tables'
-- own "default now()" applies at apply-time so this file's own content
-- (and hash) never depends on when it was generated or applied.

begin;

insert into openserp_query_rotation_state
  (query_id, query_universe_version, query_definition_hash, last_executed_at, next_eligible_at, failure_count, successful_run_count, discovery_yield, last_engine, last_run_id)
values
${rotationRows}
on conflict (query_id) do nothing;

insert into openserp_engine_budget_state
  (engine, state_version, current_budget, consecutive_failures, captcha_count, rate_limit_count, timeout_count, suspended_until, last_success_at, last_failure_at, last_run_id)
values
${budgetRows}
on conflict (engine) do nothing;

commit;
`;

  writeFileSync(OUT_SQL_PATH, sql, "utf8");
  const seedSqlSha256 = sha256(sql);

  const manifestCore = {
    mission: "OPENSERP-SERVERLESS-STATE-PERSISTENCE-1",
    query_universe_version: universe.universe_version,
    query_definition_count: universe.queries.length,
    query_state_rows: universe.queries.length,
    engine_state_rows: KNOWN_ENGINES.length,
    engines: KNOWN_ENGINES,
    budget_bounds: { min: MIN_BUDGET, start: START_BUDGET, max: MAX_BUDGET },
    additive: true,
    idempotent: true,
    transactional: true,
    deletes_rows: false,
    modifies_listings: false,
    contains_url_snippet_or_pii: false,
    seed_sql_sha256: seedSqlSha256,
  };
  const seedManifestSha256 = sha256(JSON.stringify(manifestCore));

  const manifest = { ...manifestCore, seed_manifest_sha256: seedManifestSha256, generated_at_utc: new Date().toISOString() };
  writeFileSync(OUT_MANIFEST_PATH, JSON.stringify(manifest, null, 2), "utf8");

  console.log(JSON.stringify({ ...manifest, note: "generated_at_utc is documentary only, excluded from both hashes" }, null, 2));
}

main();
