"use client";
import type { CSSProperties } from "react";
import { NeighborhoodVisualIdentityOverlay } from "@/components/search/NeighborhoodVisualIdentityOverlay";
import { PropertySelectionProvider } from "@/components/search/PropertySelectionProvider";
import { SearchListingCardDark } from "@/components/search/SearchListingCardDark";
import { LES_ORANGERS_NEIGHBORHOOD_VISUALS } from "@/lib/contextual-illustrations/les-orangers-neighborhood-visuals";
import type { Listing } from "@/lib/listings/types";

const paths={signature:"/__qa/les-orangers-signature.jpg",immobilier:"/__qa/les-orangers-immobilier.jpg",lifestyle:"/__qa/les-orangers-lifestyle.jpg"} as const;
const listing=(i:number,role:string):Listing=>({id:`qa-les-orangers-${role}`,title:"Bien aux Orangers — aperçu de certification",city:"Rabat",neighborhood:"Les Orangers",price:2850000+i*225000,currency:"DH",surface_m2:145+i*20,price_per_m2:null,property_type:"Appartement",transaction_type:"buy",bedrooms:3,bathrooms:2,freshness_label:"Source vérifiée",source_type:"Source analysée",reliability_label:"Infos limitées",reliability_score:0,reliability_available:false,is_mre_friendly:false,description:"Fixture QA uniquement",image_url:"",reliability_explanation:"Certification visuelle",listing_url:"#",source_name:"Fixture QA AkarFinder",source_display_type:"external_web_result",source_badge:"external_web_result",search_result_display_mode:"thin_indexed_result",result_origin:"search_api",original_source_required:true,allowed_ctas:["view_original"],can_show_result:true,can_show_thumbnail:false,can_show_contact:false,can_show_gallery:false,production_allowed:true,display_images:{policy:"no_listing_image"},image_permission_status:"unknown",source_access_level:"indexed_only"});

export function LesOrangersNeighborhoodVisualQAFixture(){return <PropertySelectionProvider><section data-les-orangers-visual-qa-grid className="grid grid-cols-2 gap-x-2.5 gap-y-6 lg:grid-cols-4 lg:gap-x-3">{LES_ORANGERS_NEIGHBORHOOD_VISUALS.map((v,i)=><div key={v.id} data-les-orangers-qa-card data-scene-role={v.sceneRole} data-visual-id={v.id} style={{"--les-orangers-source":`url(${paths[v.sceneRole]})`} as CSSProperties} className="relative min-w-0 [&_[data-neighborhood-photo-credit]]:hidden [&_[data-neighborhood-photo-disclosure]]:hidden [&_[data-neighborhood-photo-title]]:hidden"><SearchListingCardDark listing={listing(i,v.sceneRole)}/><div className="pointer-events-none absolute left-px right-px top-px z-10 h-[163px] overflow-hidden rounded-t-[19px] sm:h-[195px] sm:rounded-t-[15px]"><NeighborhoodVisualIdentityOverlay neighborhood={v.title} city={v.cityLabel} descriptors={v.descriptors} disclosureLabel={v.presentation.disclosureLabel}/></div><div data-les-orangers-qa-credit className="mt-1.5 truncate text-[9px] font-semibold text-muted-foreground/80">{v.source.author} · {v.source.license} · {v.source.sourceName}</div></div>)}</section><style jsx global>{`[data-les-orangers-qa-card] [data-card-image]>div:first-child{opacity:0!important}[data-les-orangers-qa-card] [data-card-image]::before{content:"";position:absolute;inset:0;background-image:var(--les-orangers-source);background-position:center;background-size:cover}`}</style></PropertySelectionProvider>}
