"use client";
import type { CSSProperties } from "react";
import { NeighborhoodVisualIdentityOverlay } from "@/components/search/NeighborhoodVisualIdentityOverlay";
import { PropertySelectionProvider } from "@/components/search/PropertySelectionProvider";
import { SearchListingCardDark } from "@/components/search/SearchListingCardDark";
import { MEDINA_NEIGHBORHOOD_VISUALS } from "@/lib/contextual-illustrations/medina-neighborhood-visuals";
import type { Listing } from "@/lib/listings/types";
const paths={signature:"/__qa/medina-signature.jpg",immobilier:"/__qa/medina-immobilier.jpg",lifestyle:"/__qa/medina-lifestyle.jpg"} as const;
function qaListing(index:number,role:string):Listing{return {id:`medina-visual-qa-${role}`,title:"Aperçu de certification Médina",city:"Rabat",neighborhood:"Médina",price:2000000+index*100000,currency:"DH",surface_m2:120+index*10,price_per_m2:null,property_type:"Riad",transaction_type:"buy",bedrooms:3,bathrooms:2,freshness_label:"Source vérifiée",source_type:"Source analysée",reliability_label:"Infos limitées",reliability_score:0,reliability_available:false,is_mre_friendly:false,description:"Fixture QA",image_url:"",reliability_explanation:"Fixture de certification visuelle",listing_url:`https://example.com/qa/medina/${role}`,source_name:"Fixture QA AkarFinder",source_display_type:"external_web_result",source_badge:"external_web_result",search_result_display_mode:"thin_indexed_result",result_origin:"search_api",original_source_required:true,allowed_ctas:["view_original"],can_show_result:true,can_show_thumbnail:false,can_show_contact:false,can_show_gallery:false,production_allowed:true,display_images:{policy:"no_listing_image"},image_permission_status:"unknown",source_access_level:"indexed_only"};}
export function MedinaNeighborhoodVisualQAFixture(){return <PropertySelectionProvider><section data-medina-visual-qa-grid className="grid grid-cols-2 gap-x-2.5 gap-y-6 lg:grid-cols-4 lg:gap-x-3">{MEDINA_NEIGHBORHOOD_VISUALS.map((v,i)=><div key={v.id} data-medina-qa-card data-scene-role={v.sceneRole} data-visual-id={v.id} style={{"--medina-source":`url(${paths[v.sceneRole]})`} as CSSProperties} className="relative min-w-0 [&_[data-neighborhood-photo-credit]]:hidden [&_[data-neighborhood-photo-disclosure]]:hidden [&_[data-neighborhood-photo-title]]:hidden"><SearchListingCardDark listing={qaListing(i,v.sceneRole)}/><div className="pointer-events-none absolute left-px right-px top-px z-10 h-[163px] overflow-hidden rounded-t-[19px] sm:h-[195px] sm:rounded-t-[15px]"><NeighborhoodVisualIdentityOverlay neighborhood={v.title} city={v.cityLabel} descriptors={v.descriptors} disclosureLabel={v.presentation.disclosureLabel}/></div><div data-medina-qa-credit className="mt-1.5 truncate text-[9px] font-semibold text-muted-foreground/80">{v.source.author} · {v.source.license} · {v.source.sourceName}</div></div>)}</section><style jsx global>{`[data-medina-qa-card] [data-card-image]>div:first-child{opacity:0!important}[data-medina-qa-card] [data-card-image]::before{content:"";position:absolute;inset:0;background-image:var(--medina-source);background-position:center;background-size:cover}`}</style></PropertySelectionProvider>}
