"use client";
import type { CSSProperties } from "react";
import { NeighborhoodVisualIdentityOverlay } from "@/components/search/NeighborhoodVisualIdentityOverlay";
import { PropertySelectionProvider } from "@/components/search/PropertySelectionProvider";
import { SearchListingCardDark } from "@/components/search/SearchListingCardDark";
import { OCEAN_NEIGHBORHOOD_VISUALS } from "@/lib/contextual-illustrations/ocean-neighborhood-visuals";
import type { Listing } from "@/lib/listings/types";
const paths={signature:"/__qa/ocean-signature.jpg",immobilier:"/__qa/ocean-immobilier.jpg",lifestyle:"/__qa/ocean-lifestyle.jpg"} as const;
function listing(index:number,role:string){return {id:`ocean-qa-${role}`,title:"Aperçu de certification Océan",city:"Rabat",neighborhood:"Océan",price:1900000+index*150000,currency:"DH",surface_m2:110+index*15,property_type:"Appartement",transaction_type:"buy",bedrooms:3,bathrooms:2,display_images:{policy:"no_listing_image"},production_allowed:true,can_show_result:true} as unknown as Listing;}
export function OceanNeighborhoodVisualQAFixture(){return <PropertySelectionProvider><section data-ocean-visual-qa-grid className="grid grid-cols-2 gap-x-2.5 gap-y-6 lg:grid-cols-3 lg:gap-x-3">{OCEAN_NEIGHBORHOOD_VISUALS.map((v,i)=><div key={v.id} data-ocean-qa-card data-scene-role={v.sceneRole} data-visual-id={v.id} style={{"--ocean-source":`url(${paths[v.sceneRole]})`} as CSSProperties} className="relative min-w-0 [&_[data-neighborhood-photo-credit]]:hidden [&_[data-neighborhood-photo-disclosure]]:hidden [&_[data-neighborhood-photo-title]]:hidden"><SearchListingCardDark listing={listing(i,v.sceneRole)}/><div className="pointer-events-none absolute left-px right-px top-px z-10 h-[163px] overflow-hidden rounded-t-[19px] sm:h-[195px] sm:rounded-t-[15px]"><NeighborhoodVisualIdentityOverlay neighborhood={v.title} city={v.cityLabel} descriptors={v.descriptors} disclosureLabel={v.presentation.disclosureLabel}/></div><div data-ocean-qa-credit className="mt-1.5 truncate text-[9px] font-semibold text-muted-foreground/80">{v.source.author} · {v.source.license} · {v.source.sourceName}</div></div>)}</section><style jsx global>{`[data-ocean-qa-card] [data-card-image]>div:first-child{opacity:0!important}[data-ocean-qa-card] [data-card-image]::before{content:"";position:absolute;inset:0;background-image:var(--ocean-source);background-position:center;background-size:cover}`}</style></PropertySelectionProvider>}
