"use client";
import type { CSSProperties } from "react";
import { NeighborhoodVisualIdentityOverlay } from "@/components/search/NeighborhoodVisualIdentityOverlay";
import { PropertySelectionProvider } from "@/components/search/PropertySelectionProvider";
import { SearchListingCardDark } from "@/components/search/SearchListingCardDark";
import { YACOUB_EL_MANSOUR_NEIGHBORHOOD_VISUALS } from "@/lib/contextual-illustrations/yacoub-el-mansour-neighborhood-visuals";
import type { Listing } from "@/lib/listings/types";
const paths={signature:"/__qa/yacoub-signature.jpg",immobilier:"/__qa/yacoub-immobilier.jpg",lifestyle:"/__qa/yacoub-lifestyle.jpg"} as const;
function listing(index:number,role:string){return {id:`yacoub-qa-${role}`,title:"Aperçu de certification Yacoub El Mansour",city:"Rabat",neighborhood:"Yacoub El Mansour",price:1700000+index*200000,currency:"DH",surface_m2:105+index*20,property_type:index===0?"Maison":"Appartement",transaction_type:"buy",bedrooms:3,bathrooms:2,display_images:{policy:"no_listing_image"},production_allowed:true,can_show_result:true} as unknown as Listing;}
export function YacoubElMansourNeighborhoodVisualQAFixture(){return <PropertySelectionProvider><section data-yacoub-visual-qa-grid className="grid grid-cols-2 gap-x-2.5 gap-y-6 lg:grid-cols-3 lg:gap-x-3">{YACOUB_EL_MANSOUR_NEIGHBORHOOD_VISUALS.map((v,i)=><div key={v.id} data-yacoub-qa-card data-scene-role={v.sceneRole} data-visual-id={v.id} style={{"--yacoub-source":`url(${paths[v.sceneRole]})`} as CSSProperties} className="relative min-w-0 [&_[data-neighborhood-photo-credit]]:hidden [&_[data-neighborhood-photo-disclosure]]:hidden [&_[data-neighborhood-photo-title]]:hidden"><SearchListingCardDark listing={listing(i,v.sceneRole)}/><div className="pointer-events-none absolute left-px right-px top-px z-10 h-[163px] overflow-hidden rounded-t-[19px] sm:h-[195px] sm:rounded-t-[15px]"><NeighborhoodVisualIdentityOverlay neighborhood={v.title} city={v.cityLabel} descriptors={v.descriptors} disclosureLabel={v.presentation.disclosureLabel}/></div><div data-yacoub-qa-credit className="mt-1.5 truncate text-[9px] font-semibold text-muted-foreground/80">{v.source.author} · {v.source.license} · {v.source.sourceName}</div></div>)}</section><style jsx global>{`[data-yacoub-qa-card] [data-card-image]>div:first-child{opacity:0!important}[data-yacoub-qa-card] [data-card-image]::before{content:"";position:absolute;inset:0;background-image:var(--yacoub-source);background-position:center;background-size:cover}`}</style></PropertySelectionProvider>}
