import { normalizePublicPropertyIndexRecord } from "./normalize-index-record";
import type { PublicPropertyIndexRecord } from "./types";

type FixtureInput = {
  id: string;
  source_host: string;
  source_url: string;
  title: string;
  short_snippet: string;
  inferred_city: string;
  inferred_neighborhood: string;
  inferred_property_type: PublicPropertyIndexRecord["inferred_property_type"];
  inferred_transaction_type: PublicPropertyIndexRecord["inferred_transaction_type"];
  public_price: number;
  public_surface: number;
  observed_at: string;
  provider_engine: PublicPropertyIndexRecord["provider_engine"];
};

function fixture(input: FixtureInput): PublicPropertyIndexRecord {
  return normalizePublicPropertyIndexRecord({
    ...input,
    result_source: "manual_seed",
    observation_count: 1,
    created_at: input.observed_at,
    updated_at: input.observed_at,
  });
}

const OBSERVED_AT = "2026-07-09T10:00:00.000Z";

export const PUBLIC_PROPERTY_INDEX_FIXTURES: PublicPropertyIndexRecord[] = [
  fixture({
    id: "casablanca-maarif-1",
    source_host: "example-listings.ma",
    source_url: "https://example-listings.ma/casablanca/maarif/appartement-1",
    title: "Appartement lumineux a vendre a Maarif, Casablanca",
    short_snippet: "Appartement 92 m2, 1 480 000 DH, vue degagee, quartier central.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Maarif",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 1480000,
    public_surface: 92,
    observed_at: OBSERVED_AT,
    provider_engine: "bing",
  }),
  fixture({
    id: "casablanca-maarif-2",
    source_host: "example-agency.ma",
    source_url: "https://example-agency.ma/casablanca/maarif/studio-2",
    title: "Studio a louer a Maarif",
    short_snippet: "Studio meuble 48 m2, 7 500 DH, proche tram.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Maarif",
    inferred_property_type: "Studio",
    inferred_transaction_type: "rent",
    public_price: 7500,
    public_surface: 48,
    observed_at: "2026-07-09T09:55:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "casablanca-racine-1",
    source_host: "example-promoteur.ma",
    source_url: "https://example-promoteur.ma/casablanca/racine/appartement-1",
    title: "Appartement a vendre a Racine, Casablanca",
    short_snippet: "Appartement 120 m2, 2 350 000 DH, balcon et parking.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Racine",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 2350000,
    public_surface: 120,
    observed_at: "2026-07-09T09:50:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "casablanca-ain-diab-1",
    source_host: "example-villa.ma",
    source_url: "https://example-villa.ma/casablanca/ain-diab/villa-1",
    title: "Villa a vendre a Ain Diab",
    short_snippet: "Villa 340 m2, 8 900 000 DH, piscine et jardin.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Ain Diab",
    inferred_property_type: "Villa",
    inferred_transaction_type: "buy",
    public_price: 8900000,
    public_surface: 340,
    observed_at: "2026-07-09T09:48:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "casablanca-bourgogne-1",
    source_host: "example-listings.ma",
    source_url: "https://example-listings.ma/casablanca/bourgogne/studio-1",
    title: "Studio a louer a Bourgogne",
    short_snippet: "Studio 36 m2, 5 200 DH, meuble simple.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Bourgogne",
    inferred_property_type: "Studio",
    inferred_transaction_type: "rent",
    public_price: 5200,
    public_surface: 36,
    observed_at: "2026-07-09T09:45:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "casablanca-fc-city-1",
    source_host: "example-projects.ma",
    source_url: "https://example-projects.ma/casablanca/finance-city/projet-1",
    title: "Programme neuf a Casablanca Finance City",
    short_snippet: "Appartement neuf 78 m2, a partir de 1 650 000 DH.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Finance City",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "new",
    public_price: 1650000,
    public_surface: 78,
    observed_at: "2026-07-09T09:43:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "rabat-agdal-1",
    source_host: "example-rabat.ma",
    source_url: "https://example-rabat.ma/rabat/agdal/appartement-1",
    title: "Appartement a vendre a Agdal, Rabat",
    short_snippet: "Appartement 104 m2, 1 920 000 DH, ascenseur et balcon.",
    inferred_city: "Rabat",
    inferred_neighborhood: "Agdal",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 1920000,
    public_surface: 104,
    observed_at: "2026-07-09T09:40:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "rabat-souissi-1",
    source_host: "example-rabat.ma",
    source_url: "https://example-rabat.ma/rabat/souissi/villa-1",
    title: "Villa a vendre a Souissi",
    short_snippet: "Villa 410 m2, 12 500 000 DH, jardin mature.",
    inferred_city: "Rabat",
    inferred_neighborhood: "Souissi",
    inferred_property_type: "Villa",
    inferred_transaction_type: "buy",
    public_price: 12500000,
    public_surface: 410,
    observed_at: "2026-07-09T09:38:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "rabat-hay-riad-1",
    source_host: "example-office.ma",
    source_url: "https://example-office.ma/rabat/hay-riad/bureau-1",
    title: "Bureau a louer a Hay Riad",
    short_snippet: "Bureau 85 m2, 16 000 DH, espace flexible.",
    inferred_city: "Rabat",
    inferred_neighborhood: "Hay Riad",
    inferred_property_type: "Bureau",
    inferred_transaction_type: "rent",
    public_price: 16000,
    public_surface: 85,
    observed_at: "2026-07-09T09:36:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "marrakech-gueliz-1",
    source_host: "example-marrakech.ma",
    source_url: "https://example-marrakech.ma/marrakech/gueliz/appartement-1",
    title: "Appartement a vendre a Gueliz, Marrakech",
    short_snippet: "Appartement 88 m2, 1 260 000 DH, terrasse et luminosite.",
    inferred_city: "Marrakech",
    inferred_neighborhood: "Gueliz",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 1260000,
    public_surface: 88,
    observed_at: "2026-07-09T09:34:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "marrakech-hivernage-1",
    source_host: "example-marrakech.ma",
    source_url: "https://example-marrakech.ma/marrakech/hivernage/appartement-1",
    title: "Appartement a vendre a Hivernage",
    short_snippet: "Appartement 134 m2, 3 200 000 DH, residence calme.",
    inferred_city: "Marrakech",
    inferred_neighborhood: "Hivernage",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 3200000,
    public_surface: 134,
    observed_at: "2026-07-09T09:32:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "marrakech-route-ourika-1",
    source_host: "example-villa.ma",
    source_url: "https://example-villa.ma/marrakech/ourika/villa-1",
    title: "Villa a vendre sur la route de l'Ourika",
    short_snippet: "Villa 280 m2, 4 600 000 DH, jardin et piscine.",
    inferred_city: "Marrakech",
    inferred_neighborhood: "Route de l'Ourika",
    inferred_property_type: "Villa",
    inferred_transaction_type: "buy",
    public_price: 4600000,
    public_surface: 280,
    observed_at: "2026-07-09T09:30:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "tanger-malabata-1",
    source_host: "example-tanger.ma",
    source_url: "https://example-tanger.ma/tanger/malabata/appartement-1",
    title: "Appartement a vendre a Malabata, Tanger",
    short_snippet: "Appartement 96 m2, 1 540 000 DH, proche corniche.",
    inferred_city: "Tanger",
    inferred_neighborhood: "Malabata",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 1540000,
    public_surface: 96,
    observed_at: "2026-07-09T09:28:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "tanger-centre-1",
    source_host: "example-tanger.ma",
    source_url: "https://example-tanger.ma/tanger/centre/studio-1",
    title: "Studio a louer au centre-ville de Tanger",
    short_snippet: "Studio 42 m2, 4 800 DH, proche gare.",
    inferred_city: "Tanger",
    inferred_neighborhood: "Centre Ville",
    inferred_property_type: "Studio",
    inferred_transaction_type: "rent",
    public_price: 4800,
    public_surface: 42,
    observed_at: "2026-07-09T09:26:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "agadir-founty-1",
    source_host: "example-agadir.ma",
    source_url: "https://example-agadir.ma/agadir/founty/appartement-1",
    title: "Appartement a vendre a Founty, Agadir",
    short_snippet: "Appartement 110 m2, 1 680 000 DH, proche plage.",
    inferred_city: "Agadir",
    inferred_neighborhood: "Founty",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 1680000,
    public_surface: 110,
    observed_at: "2026-07-09T09:24:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "agadir-marina-1",
    source_host: "example-agadir.ma",
    source_url: "https://example-agadir.ma/agadir/marina/villa-1",
    title: "Villa a louer a la Marina, Agadir",
    short_snippet: "Villa 300 m2, 22 000 DH, vue ocean.",
    inferred_city: "Agadir",
    inferred_neighborhood: "Marina",
    inferred_property_type: "Villa",
    inferred_transaction_type: "rent",
    public_price: 22000,
    public_surface: 300,
    observed_at: "2026-07-09T09:22:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "fes-ville-nouvelle-1",
    source_host: "example-fes.ma",
    source_url: "https://example-fes.ma/fes/ville-nouvelle/appartement-1",
    title: "Appartement a vendre a Ville Nouvelle, Fes",
    short_snippet: "Appartement 86 m2, 980 000 DH, residence recente.",
    inferred_city: "Fes",
    inferred_neighborhood: "Ville Nouvelle",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 980000,
    public_surface: 86,
    observed_at: "2026-07-09T09:20:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "meknes-hamria-1",
    source_host: "example-meknes.ma",
    source_url: "https://example-meknes.ma/meknes/hamria/appartement-1",
    title: "Appartement a louer a Hamria, Meknes",
    short_snippet: "Appartement 74 m2, 3 900 DH, proche commerces.",
    inferred_city: "Meknes",
    inferred_neighborhood: "Hamria",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "rent",
    public_price: 3900,
    public_surface: 74,
    observed_at: "2026-07-09T09:18:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "kenitra-maamora-1",
    source_host: "example-kenitra.ma",
    source_url: "https://example-kenitra.ma/kenitra/maamora/appartement-1",
    title: "Appartement a vendre a Maamora, Kenitra",
    short_snippet: "Appartement 90 m2, 860 000 DH, premier etage.",
    inferred_city: "Kenitra",
    inferred_neighborhood: "Maamora",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 860000,
    public_surface: 90,
    observed_at: "2026-07-09T09:16:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "mohammedia-parc-1",
    source_host: "example-moha.ma",
    source_url: "https://example-moha.ma/mohammedia/parc/studio-1",
    title: "Studio a louer a Parc, Mohammedia",
    short_snippet: "Studio 31 m2, 3 500 DH, quartier calme.",
    inferred_city: "Mohammedia",
    inferred_neighborhood: "Parc",
    inferred_property_type: "Studio",
    inferred_transaction_type: "rent",
    public_price: 3500,
    public_surface: 31,
    observed_at: "2026-07-09T09:14:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "el-jadida-centre-1",
    source_host: "example-jadida.ma",
    source_url: "https://example-jadida.ma/el-jadida/centre/appartement-1",
    title: "Appartement a vendre au centre d'El Jadida",
    short_snippet: "Appartement 82 m2, 780 000 DH, vue degagee.",
    inferred_city: "El Jadida",
    inferred_neighborhood: "Centre Ville",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 780000,
    public_surface: 82,
    observed_at: "2026-07-09T09:12:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "sale-tabriquet-1",
    source_host: "example-sale.ma",
    source_url: "https://example-sale.ma/sale/tabriquet/appartement-1",
    title: "Appartement a louer a Tabriquet, Sale",
    short_snippet: "Appartement 67 m2, 4 600 DH, acces rapide tram.",
    inferred_city: "Sale",
    inferred_neighborhood: "Tabriquet",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "rent",
    public_price: 4600,
    public_surface: 67,
    observed_at: "2026-07-09T09:10:00.000Z",
    provider_engine: "ecosia",
  }),
  fixture({
    id: "casablanca-anfa-1",
    source_host: "example-casa.ma",
    source_url: "https://example-casa.ma/casablanca/anfa/appartement-1",
    title: "Appartement a louer a Anfa, Casablanca",
    short_snippet: "Appartement 118 m2, 12 500 DH, residence securisee.",
    inferred_city: "Casablanca",
    inferred_neighborhood: "Anfa",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "rent",
    public_price: 12500,
    public_surface: 118,
    observed_at: "2026-07-09T09:08:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "rabat-hassan-1",
    source_host: "example-rabat.ma",
    source_url: "https://example-rabat.ma/rabat/hassan/appartement-1",
    title: "Appartement a vendre a Hassan, Rabat",
    short_snippet: "Appartement 101 m2, 1 730 000 DH, bon acces centre.",
    inferred_city: "Rabat",
    inferred_neighborhood: "Hassan",
    inferred_property_type: "Appartement",
    inferred_transaction_type: "buy",
    public_price: 1730000,
    public_surface: 101,
    observed_at: "2026-07-09T09:06:00.000Z",
    provider_engine: "bing",
  }),
  fixture({
    id: "tanger-drissia-1",
    source_host: "example-tanger.ma",
    source_url: "https://example-tanger.ma/tanger/drissia/bureau-1",
    title: "Bureau a vendre a Drissia, Tanger",
    short_snippet: "Bureau 92 m2, 1 120 000 DH, usage mixte possible.",
    inferred_city: "Tanger",
    inferred_neighborhood: "Drissia",
    inferred_property_type: "Bureau",
    inferred_transaction_type: "buy",
    public_price: 1120000,
    public_surface: 92,
    observed_at: "2026-07-09T09:04:00.000Z",
    provider_engine: "ecosia",
  }),
];
