import { createClient } from "npm:@supabase/supabase-js@2";

type AssetSpec = { role:"signature"|"immobilier"|"lifestyle"; sourceUrl:string; storagePath:string; width:number; height:number; bytes:number; sha1:string; };
const BUCKET="neighborhood-visuals";
const COMMONS="https://commons.wikimedia.org/wiki/Special:Redirect/file/";
const ASSETS: readonly AssetSpec[] = [
  { role:"signature", sourceUrl:`${COMMONS}Old%20Medina%20of%20Rabat.jpg`, storagePath:"rabat/medina/signature/master.jpg", width:1136,height:640,bytes:142882,sha1:"6867e5f4d6a6891f13c167ba1a9eaaea266793ff" },
  { role:"immobilier", sourceUrl:`${COMMONS}Mosque%20in%20the%20medina%20of%20Rabat%20%2812366658684%29.jpg`, storagePath:"rabat/medina/immobilier/master.jpg", width:3906,height:2602,bytes:6448483,sha1:"4d41183ad3ca272837e1d668cc3433ad967a72ba" },
  { role:"lifestyle", sourceUrl:`${COMMONS}Market%20Stalls%20and%20Thatched%20Roof%20-%20Medina%20%28Old%20City%29%20-%20Rabat%20-%20Morocco.jpg`, storagePath:"rabat/medina/lifestyle/master.jpg", width:2304,height:3456,bytes:3251457,sha1:"d2a1ba64022489a7d501b6cb649d8291f1d591f2" },
] as const;

function jpegDimensions(bytes:Uint8Array){if(bytes.length<4||bytes[0]!==0xff||bytes[1]!==0xd8)throw new Error("source is not a JPEG");let o=2;while(o+8<bytes.length){if(bytes[o]!==0xff){o++;continue;}const m=bytes[o+1];o+=2;if(m===0xd8||m===0xd9)continue;if(o+2>bytes.length)break;const l=(bytes[o]<<8)|bytes[o+1];if(l<2||o+l>bytes.length)break;if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(m))return{height:(bytes[o+3]<<8)|bytes[o+4],width:(bytes[o+5]<<8)|bytes[o+6]};o+=l;}throw new Error("JPEG dimensions could not be decoded");}
async function sha1Hex(bytes:Uint8Array){const exact=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const digest=await crypto.subtle.digest("SHA-1",exact);return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,"0")).join("");}

Deno.serve(async(req:Request)=>{if(req.method!=="POST")return new Response("POST required",{status:405});const body=await req.json().catch(()=>null) as {lot?:string;confirmExactSources?:boolean}|null;if(body?.lot!=="P1.7-MEDINA"||body.confirmExactSources!==true)return Response.json({error:"bounded P1.7 confirmation required"},{status:400});const url=Deno.env.get("SUPABASE_URL");const raw=Deno.env.get("SUPABASE_SECRET_KEYS");const legacy=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");const key=raw?JSON.parse(raw).default:legacy;if(!url||!key)return Response.json({error:"admin storage environment unavailable"},{status:500});const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const results=[];for(const asset of ASSETS){const response=await fetch(asset.sourceUrl,{headers:{"User-Agent":"AkarFinder-P1.7-Medina/1.0"},redirect:"follow"});if(!response.ok)throw new Error(`${asset.role}: source fetch failed ${response.status}`);const bytes=new Uint8Array(await response.arrayBuffer());const dims=jpegDimensions(bytes);if(dims.width!==asset.width||dims.height!==asset.height)throw new Error(`${asset.role}: dimension drift`);if(bytes.byteLength!==asset.bytes)throw new Error(`${asset.role}: byte-size drift`);const sha1=await sha1Hex(bytes);if(sha1!==asset.sha1)throw new Error(`${asset.role}: SHA-1 mismatch`);const exact=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;const {data,error}=await admin.storage.from(BUCKET).upload(asset.storagePath,new Blob([exact],{type:"image/jpeg"}),{contentType:"image/jpeg",cacheControl:"31536000",upsert:true});if(error)throw new Error(`${asset.role}: storage upload failed: ${error.message}`);results.push({role:asset.role,path:data.path,width:dims.width,height:dims.height,bytes:bytes.byteLength,sha1});}return Response.json({lot:"P1.7-MEDINA",ingested:results.length,results});});
