import { GEO_NEIGHBORHOODS } from "./geo-entity-registry";
import type { LandmarkTerritoryEntity } from "./territory-dictionary";

export type VerifiedLandmarkEntry = {
  entity: LandmarkTerritoryEntity;
  sourceRefs: readonly [string, string, ...string[]];
  verificationNote: string;
  verifiedAt: string;
};

export const VERIFIED_LANDMARKS: readonly VerifiedLandmarkEntry[] = [
  {
    entity: {
      id: "landmark_casablanca_finance_city_cfc_tower",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "finance-city",
      landmarkSlug: "cfc-tower",
      canonicalName: "CFC First Tower",
      aliases: ["Casablanca Finance City Tower", "Tour CFC"],
      category: "business",
      parentId: "district_casablanca_finance_city",
      importance: {
        score: 95,
        tier: "major",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: {
        lat: 33.56358,
        lng: -7.66096,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://casablancafinancecity.com/sites/default/files/2025-09/RA_Print_compressed%20%281%29.pdf",
      "https://mapcarta.com/W871612907",
    ],
    verificationNote: "Official CFC address + OSM/Wikidata-backed point; parent district is canonical Casablanca Finance City.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_rabat_agdal_station",
      type: "landmark",
      citySlug: "rabat",
      districtSlug: "agdal",
      landmarkSlug: "gare-rabat-agdal",
      canonicalName: "Gare Rabat-Agdal",
      aliases: ["Rabat Agdal Station", "Gare d’Agdal"],
      category: "transport",
      parentId: "district_rabat_agdal",
      importance: {
        score: 100,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 34.0012,
        lng: -6.85739,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.oncf.ma/en/content/download/37209/850874/file/Gare%20de%20Rabat-agdal%20-%20VF.pdf",
      "https://mapcarta.com/W654504928",
    ],
    verificationNote: "ONCF confirms Rabat-Agdal and its Agdal side; OSM-backed point confirms the station location.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_marrakech_hivernage_menara_mall",
      type: "landmark",
      citySlug: "marrakech",
      districtSlug: "hivernage",
      landmarkSlug: "menara-mall",
      canonicalName: "Menara Mall",
      aliases: ["Ménara Mall"],
      category: "retail",
      parentId: "district_marrakech_hivernage",
      importance: {
        score: 95,
        tier: "major",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: {
        lat: 31.61806,
        lng: -8.00974,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.menaramall.com/",
      "https://visitmarrakech.com/listing/menara-mall/",
      "https://mapcarta.com/fr/N3320049181",
    ],
    verificationNote: "Official mall + official Marrakech guide + OSM-backed point support identity, Hivernage association and coordinates.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_fes_el_bali_bab_bou_jeloud",
      type: "landmark",
      citySlug: "fes",
      districtSlug: "fes-el-bali",
      landmarkSlug: "bab-bou-jeloud",
      canonicalName: "Bab Bou Jeloud",
      aliases: ["Bab Boujloud", "Porte Bleue"],
      category: "heritage",
      parentId: "district_fes_el_bali",
      importance: {
        score: 100,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: {
        lat: 34.0617,
        lng: -4.98402,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.wikidata.org/wiki/Q2881543",
      "https://mapcarta.com/W574667510",
    ],
    verificationNote: "Wikidata identifies Bab Bou Jeloud as part of the Medina of Fez; the independent OSM-backed point agrees on the gate coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_agadir_talborjt_mosquee_mohamed_v",
      type: "landmark",
      citySlug: "agadir",
      districtSlug: "talborjt",
      landmarkSlug: "mosquee-mohamed-v",
      canonicalName: "Mosquée Mohamed V",
      aliases: ["Mosque Mohammed V", "Mosquée Mohammed V"],
      category: "worship",
      parentId: "district_agadir_talborjt",
      importance: {
        score: 98,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 30.42215,
        lng: -9.59252,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://agadirmonuments.com/agadir-monuments-la-mosquee-mohamed-v/",
      "https://www.barcelo.com/guia-turismo/fr/maroc/agadir/a-voir-et-a-faire/mosquees-agadir/",
      "https://mapcarta.com/29431532",
    ],
    verificationNote: "Two independent descriptive sources place the mosque in Nouveau Talborjt; the OSM-backed point provides the verified coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_casablanca_maarif_stade_mohammed_v",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "maarif",
      landmarkSlug: "stade-mohammed-v",
      canonicalName: "Stade Mohammed V",
      aliases: ["Complexe Sportif Mohammed V", "Complexe Mohammed V", "Donor"],
      category: "sports",
      parentId: "district_casablanca_maarif",
      importance: {
        score: 99,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.2, retainPriority: true },
      coordinates: {
        lat: 33.58285065,
        lng: -7.6468283,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.sonarges.ma/infrastructures/complexe-sportif-mohamed-v/",
      "https://www.casablancacity.ma/fr/article/193/annexes-du-complexe-sportif-mohamed-v",
      "https://www.openstreetmap.org/way/1349843482",
    ],
    verificationNote: "SONARGES and CasablancaCity independently place Complexe Mohammed V in Maârif; the immutable point comes from the verified OSM stadium way retained by the Landmark Factory PIP batch.",
    verifiedAt: "2026-09-20",
  },
  {
    entity: {
      id: "landmark_casablanca_maarif_twin_center",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "maarif",
      landmarkSlug: "twin-center",
      canonicalName: "Twin Center",
      aliases: ["Casablanca Twin Center", "Twin Centre"],
      category: "business",
      parentId: "district_casablanca_maarif",
      importance: {
        score: 98,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: {
        lat: 33.58658,
        lng: -7.63229,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://visitcasablanca.ma/pois/twin-center/",
      "https://mapcarta.com/17432488",
      "https://www.wikidata.org/wiki/Q2743636",
    ],
    verificationNote: "Visit Casablanca explicitly places Twin Center in Maârif; Mapcarta/Wikidata agree on the landmark point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_casablanca_ain_diab_morocco_mall",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "ain-diab",
      landmarkSlug: "morocco-mall",
      canonicalName: "Morocco Mall",
      aliases: ["Mall du Maroc"],
      category: "retail",
      parentId: "district_casablanca_ain_diab",
      importance: {
        score: 97,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 33.5758,
        lng: -7.70686,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.moroccomall.ma/plan-d-acces",
      "https://visitcasablanca.ma/pois/morocco-mall/",
      "https://mapcarta.com/W174580197",
    ],
    verificationNote: "Morocco Mall and Visit Casablanca both identify the Ain Diab address; the OSM-backed point supplies the verified coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_marrakech_gueliz_carre_eden",
      type: "landmark",
      citySlug: "marrakech",
      districtSlug: "gueliz",
      landmarkSlug: "carre-eden",
      canonicalName: "Carré Eden",
      aliases: ["Carré Eden Shopping Center", "Eden Square"],
      category: "retail",
      parentId: "district_marrakech_gueliz",
      importance: {
        score: 96,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 31.635103,
        lng: -8.011633,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://carreedenshoppingcenter.ma/",
      "https://visitmarrakech.com/listing/carre-eden/",
      "https://fr.wikipedia.org/wiki/Carr%C3%A9_Eden",
    ],
    verificationNote: "Official mall and official Marrakech guide explicitly place Carré Eden in Guéliz; the published point agrees with the named site.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_agadir_founty_sofitel_thalassa",
      type: "landmark",
      citySlug: "agadir",
      districtSlug: "founty",
      landmarkSlug: "sofitel-thalassa",
      canonicalName: "Sofitel Agadir Thalassa Sea & Spa",
      aliases: ["Sofitel Agadir Thalassa"],
      category: "other",
      parentId: "district_agadir_founty",
      importance: {
        score: 90,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 30.3927,
        lng: -9.597191,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://all.accor.com/hotel/5242/index.fr.shtml",
      "https://mapcarta.com/32586052",
    ],
    verificationNote: "Accor explicitly gives Cité Founty P5 and the GPS point; the independent OSM-backed source agrees closely.",
    verifiedAt: "2026-09-18",
  },

  {
    entity: {
      id: "landmark_rabat_souissi_mega_mall",
      type: "landmark",
      citySlug: "rabat",
      districtSlug: "souissi",
      landmarkSlug: "mega-mall",
      canonicalName: "Mega Mall",
      aliases: ["Mega Mall Rabat"],
      category: "retail",
      parentId: "district_rabat_souissi",
      importance: {
        score: 95,
        tier: "major",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.6, retainPriority: true },
      coordinates: {
        lat: 33.96771,
        lng: -6.83014,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitrabat.com/lieux/mega-mall/",
      "https://mapcarta.com/fr/W109711402",
    ],
    verificationNote: "Visit Rabat explicitly places Mega Mall in Souissi; the OSM-backed point provides the verified coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_rabat_hay_riad_mahaj_riad",
      type: "landmark",
      citySlug: "rabat",
      districtSlug: "hay-riad",
      landmarkSlug: "mahaj-riad",
      canonicalName: "Place Mahaj Riad",
      aliases: ["Mahaj Riad", "Mahaj Ryad"],
      category: "retail",
      parentId: "district_rabat_hay_riad",
      importance: {
        score: 97,
        tier: "flagship",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 33.96045,
        lng: -6.86748,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitrabat.com/lieux/place-mahaj-riad/",
      "https://mapcarta.com/fr/W990428959",
    ],
    verificationNote: "Visit Rabat explicitly places Place Mahaj Riad in Hay Riad; the OSM-backed point supplies the verified coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_rabat_hassan_tour_hassan",
      type: "landmark",
      citySlug: "rabat",
      districtSlug: "hassan",
      landmarkSlug: "tour-hassan",
      canonicalName: "Tour Hassan",
      aliases: ["Hassan Tower"],
      category: "heritage",
      parentId: "district_rabat_hassan",
      importance: {
        score: 100,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.3, retainPriority: true },
      coordinates: {
        lat: 34.02414,
        lng: -6.82279,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitrabat.com/lieux/tour-hassan/",
      "https://www.toutrabat.com/fr/quartiers/hassan",
      "https://mapcarta.com/fr/31907658",
    ],
    verificationNote: "Visit Rabat verifies the landmark; the Hassan district guide ties the quarter to the tower; the OSM-backed point supplies the coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_tanger_malabata_cap_malabata",
      type: "landmark",
      citySlug: "tanger",
      districtSlug: "malabata",
      landmarkSlug: "cap-malabata",
      canonicalName: "Cap Malabata",
      aliases: ["Cape Malabata", "Punta Malabata"],
      category: "other",
      parentId: "district_tanger_malabata",
      importance: {
        score: 98,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: {
        lat: 35.81802,
        lng: -5.75009,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitmorocco.com/fr/voyage/tanger",
      "https://www.barcelo.com/guia-turismo/fr/maroc/tanger/a-voir-et-a-faire/cap-malabata/",
      "https://mapcarta.com/fr/17431884",
    ],
    verificationNote: "ONMT lists Cap Malabata as a Tangier must-see; the descriptive source links the cape to the Malabata quarter; open map data provides the point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_tanger_marchan_cafe_hafa",
      type: "landmark",
      citySlug: "tanger",
      districtSlug: "marchan",
      landmarkSlug: "cafe-hafa",
      canonicalName: "Café Hafa",
      aliases: ["Cafe Hafa"],
      category: "other",
      parentId: "district_tanger_marchan",
      importance: {
        score: 96,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 35.7914,
        lng: -5.82198,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitmorocco.com/fr/voyage/tanger/medina",
      "https://www.barcelo.com/guia-turismo/fr/maroc/tanger/a-voir-et-a-faire/cafe-hafa/",
      "https://mapcarta.com/N2856148906",
    ],
    verificationNote: "ONMT confirms Café Hafa as an iconic Tangier landmark; the descriptive source explicitly places it in Marshan; OSM-backed data provides the point.",
    verifiedAt: "2026-09-18",
  },

  {
    entity: {
      id: "landmark_rabat_ocean_place_de_russie",
      type: "landmark",
      citySlug: "rabat",
      districtSlug: "ocean",
      landmarkSlug: "place-de-russie",
      canonicalName: "Place de Russie",
      aliases: ["Place de la Russie"],
      category: "transport",
      parentId: "district_rabat_ocean",
      importance: {
        score: 88,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 34.01881,
        lng: -6.85002,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.toutrabat.com/fr/quartiers/ocean",
      "https://fr.le360.ma/societe/rabat-voici-a-quoi-ressemble-le-nouveau-parking-souterrain-au-quartier-de-locean_HCXXDRDCU5CXBDYV5TIGZLGXXU/",
      "https://mapcarta.com/fr/N4592889801",
    ],
    verificationNote: "Two independent Rabat sources explicitly tie Place de Russie to Quartier Océan; OSM-backed mapping supplies the point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_tanger_ville_nouvelle_terrasse_paresseux",
      type: "landmark",
      citySlug: "tanger",
      districtSlug: "ville-nouvelle",
      landmarkSlug: "terrasse-des-paresseux",
      canonicalName: "Terrasse des Paresseux",
      aliases: ["Place Faro", "Sour Al Maâazine"],
      category: "other",
      parentId: "district_tanger_ville_nouvelle",
      importance: {
        score: 97,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 35.78086,
        lng: -5.81179,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://aut.gov.ma/patrimoine/",
      "https://www.visitmorocco.com/sites/default/files/atoms/files/Tanger%20FR.pdf",
      "https://mapcarta.com/fr/N7264187086",
    ],
    verificationNote: "Tangier Urban Agency and ONMT identify Boulevard Pasteur / Place Faro as the spine of the Ville Nouvelle; OSM-backed mapping supplies the viewpoint coordinate.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_fes_ville_nouvelle_place_florence",
      type: "landmark",
      citySlug: "fes",
      districtSlug: "ville-nouvelle",
      landmarkSlug: "place-florence",
      canonicalName: "Place Florence",
      aliases: ["Place de Florence", "Place Lyautey"],
      category: "park",
      parentId: "district_fes_ville_nouvelle",
      importance: {
        score: 94,
        tier: "major",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.6, retainPriority: true },
      coordinates: {
        lat: 34.04211,
        lng: -4.99994,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://fesparkings.ma/",
      "https://fliphtml5.com/bvhkj/uuiu/Plan_de_d%C3%A9placement_urbains_de_la_ville_de_F%C3%A8s/",
      "https://mapcarta.com/fr/W174481108",
    ],
    verificationNote: "The municipality-linked parking operator and the Fès urban mobility plan identify Place Florence in the Ville Nouvelle network; OSM-backed mapping supplies the point.",
    verifiedAt: "2026-09-18",
  },

  {
    entity: {
      id: "landmark_casablanca_bourgogne_casa_bourgogne_post",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "bourgogne",
      landmarkSlug: "casa-bourgogne-poste",
      canonicalName: "Poste Casa Bourgogne",
      aliases: ["Casa Bourgogne", "Barid Al-Maghrib Poste Casa Bourgogne"],
      category: "civic",
      parentId: "district_casablanca_bourgogne",
      importance: {
        score: 82,
        tier: "regional",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 14.0, retainPriority: false },
      coordinates: {
        lat: 33.59505,
        lng: -7.63734,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.city-info.ma/casablanca/fr/org/3001320205/3181/",
      "https://www.telecontact.ma/barid-al-maghrib-poste-casa-bourgogne/poste/casablanca/2121435",
      "https://mapcarta.com/fr/N2907752040",
    ],
    verificationNote: "Two Moroccan directory sources identify the Barid Al-Maghrib branch explicitly in Quartier Bourgogne; OSM-backed mapping supplies the point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_casablanca_bouskoura_forest",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "bouskoura",
      landmarkSlug: "foret-de-bouskoura",
      canonicalName: "Forêt de Bouskoura",
      aliases: ["Bouskoura Forest"],
      category: "park",
      parentId: "district_casablanca_bouskoura",
      importance: {
        score: 96,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 33.459,
        lng: -7.5918,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://visitcasablanca.ma/en/pois/foret-bouskoura/",
      "https://wecasablanca.ma/en/discover/visit-casablanca",
      "https://mapcarta.com/fr/W35157794",
    ],
    verificationNote: "Casablanca tourism sources identify the Bouskoura forest as the major peri-urban Bouskoura landmark; OSM-backed mapping supplies the forest point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_kenitra_centre_ville_kenitra_center",
      type: "landmark",
      citySlug: "kenitra",
      districtSlug: "centre-ville",
      landmarkSlug: "kenitra-center",
      canonicalName: "Kénitra Center",
      aliases: ["Kenitra Center Mall"],
      category: "retail",
      parentId: "district_kenitra_centre_ville",
      importance: {
        score: 92,
        tier: "major",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.7, retainPriority: true },
      coordinates: {
        lat: 34.26698,
        lng: -6.56446,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitrabat.com/lieux/kenitra-center/",
      "https://mapcarta.com/fr/W1280364121",
      "https://www.hespress.com/%D8%AD%D8%A7%D8%AA%D9%85-%D8%B9%D9%85%D9%88%D8%B1-%D9%8A%D8%AD%D9%8A%D9%8A-%D8%AD%D9%81%D9%84-%D8%A7%D9%81%D8%AA%D8%AA%D8%A7%D8%AD-%D8%A7%D9%84%D9%82%D9%86%D9%8A%D8%B7%D8%B1%D8%A9-%D8%B3%D8%A7-545046.html",
    ],
    verificationNote: "Visit Rabat and independent reporting place Kénitra Center in the heart of Kénitra; OSM-backed mapping supplies the point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_mohammedia_centre_parc_villes_jumelees",
      type: "landmark",
      citySlug: "mohammedia",
      districtSlug: "centre",
      landmarkSlug: "parc-des-villes-jumelees",
      canonicalName: "Parc des Villes Jumelées",
      aliases: ["Parc de Mohammedia"],
      category: "park",
      parentId: "district_mohammedia_centre",
      importance: {
        score: 92,
        tier: "major",
        basis: ["product_priority", "orientation_value"],
      },
      visibility: { minZoom: 13.7, retainPriority: true },
      coordinates: {
        lat: 33.70575,
        lng: -7.39766,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://letouriste.ma/mohammedia-la-cite-des-fleurs-et-des-sports-elegants/",
      "https://aujourdhui.ma/culture/premiere-edition-de-mohammediart-les-acteurs-culturels-et-associatifs-investissent-lespace-vert-68755",
      "https://mapcarta.com/fr/W571799684",
    ],
    verificationNote: "Independent Moroccan sources identify Parc des Villes Jumelées as a central Mohammedia landmark; OSM-backed mapping supplies the point.",
    verifiedAt: "2026-09-18",
  },

  {
    entity: {
      id: "landmark_casablanca_racine_institut_juan_ramon_jimenez",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "racine",
      landmarkSlug: "institut-juan-ramon-jimenez",
      canonicalName: "Institut Espagnol Juan Ramón Jiménez",
      aliases: ["Instituto Español Juan Ramón Jiménez", "École Juan Ramon Jimenez"],
      category: "other",
      parentId: "district_casablanca_racine",
      importance: {
        score: 88,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 33.58953,
        lng: -7.6415,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.educacionfpydeportes.gob.es/marruecos/oficinas-y-centros/centros-docentes/centros-docentes.html",
      "https://casainvest.ma/sites/default/files/Guidedelinvestisseur2022.pdf",
      "https://mapcarta.com/W1308527857",
    ],
    verificationNote: "Spanish Ministry confirms the 192 Bd d’Anfa address; the Casablanca-Settat CRI investment guide explicitly identifies the school at that address in Racine; OSM-backed mapping supplies the point.",
    verifiedAt: "2026-09-18",
  },
  {
    entity: {
      id: "landmark_marrakech_ourika_palmgolf",
      type: "landmark",
      citySlug: "marrakech",
      districtSlug: "route-de-lourika",
      landmarkSlug: "palmgolf-marrakech-ourika",
      canonicalName: "PalmGolf Marrakech Ourika",
      aliases: ["PalmGolf Ourika"],
      category: "other",
      parentId: "district_marrakech_ourika",
      importance: {
        score: 90,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 31.506329,
        lng: -7.957627,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://frmg.ma/palmgolf-marrakech-ourika/",
      "https://www.visitmorocco.com/sites/default/files/atoms/files/Golf%20In%20Morocco%20Brochure.pdf",
      "https://www.where2golf.com/morocco/palmgolf-marrakech-ourika/",
    ],
    verificationNote: "FRMG and ONMT both identify PalmGolf Marrakech Ourika at Km 12 on Route de l’Ourika; an independent golf mapping source supplies the course point.",
    verifiedAt: "2026-09-18",
  },


  {
    entity: {
      id: "landmark_meknes_ancienne_medina_bab_mansour",
      type: "landmark",
      citySlug: "meknes",
      districtSlug: "ancienne-medina",
      landmarkSlug: "bab-mansour",
      canonicalName: "Bab Mansour",
      aliases: ["Bab Mansour el Aleuj", "Bab el-Mansour"],
      category: "heritage",
      parentId: "district_meknes_ancienne_medina",
      importance: {
        score: 100,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.3, retainPriority: true },
      coordinates: {
        lat: 33.89258,
        lng: -5.56464,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitmorocco.com/fr/voyage/meknes",
      "https://mapcarta.com/fr/35844436",
    ],
    verificationNote: "ONMT explicitly identifies Bab Mansour as the gate giving access to the Meknès medina; OSM-backed Mapcarta supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_tetouan_medina_bab_el_okla",
      type: "landmark",
      citySlug: "tetouan",
      districtSlug: "medina",
      landmarkSlug: "bab-el-okla",
      canonicalName: "Bab El Oqla",
      aliases: ["Bab El-Okla", "Bab El Oqla"],
      category: "heritage",
      parentId: "district_tetouan_medina",
      importance: {
        score: 99,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: {
        lat: 35.57066,
        lng: -5.36362,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitmorocco.com/sites/default/files/atoms/files/Tetouan%20ESP.pdf",
      "https://mapcarta.com/fr/N4026734005",
    ],
    verificationNote: "ONMT lists Bab El Oqla among the seven historic gates of the Tétouan medina; OSM-backed Mapcarta supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_essaouira_medina_skala_de_la_ville",
      type: "landmark",
      citySlug: "essaouira",
      districtSlug: "medina",
      landmarkSlug: "skala-de-la-ville",
      canonicalName: "Skala de la Ville",
      aliases: ["Sqala de la Kasbah", "Skala"],
      category: "heritage",
      parentId: "district_essaouira_medina",
      importance: {
        score: 99,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: {
        lat: 31.5148025,
        lng: -9.7722691,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://whc.unesco.org/fr/list/753",
      "https://www.google.com/maps/place/Skala+de+la+Ville/",
    ],
    verificationNote: "UNESCO certifies the fortified medina fabric of Essaouira; the Skala is on the medina rampart and Google Maps supplies the public point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_sale_bab_lamrissa_bab_el_mrissa",
      type: "landmark",
      citySlug: "sale",
      districtSlug: "bab-lamrissa",
      landmarkSlug: "bab-el-mrissa",
      canonicalName: "Bab el-Mrissa",
      aliases: ["Bab Lamrissa", "Bab al-Mrissa", "Bab Mrissa"],
      category: "heritage",
      parentId: "district_sale_bab_lamrissa",
      importance: {
        score: 99,
        tier: "flagship",
        basis: ["product_priority", "orientation_value", "urban_prominence"],
      },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: {
        lat: 34.032708,
        lng: -6.820187,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.visitrabat.com/lieux/bab-el-mrissa/",
      "https://www.wikidata.org/wiki/Q2389277",
    ],
    verificationNote: "Visit Rabat identifies Bab el-Mrissa as an emblematic gate of Salé; Wikidata supplies the public coordinate and the same heritage identity.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_el_jadida_hay_salam_mosquee_hay_essalam",
      type: "landmark",
      citySlug: "el-jadida",
      districtSlug: "hay-salam",
      landmarkSlug: "mosquee-hay-essalam",
      canonicalName: "Mosquée Hay Essalam",
      aliases: ["Mosquée Hay Salam"],
      category: "civic",
      parentId: "district_el_jadida_hay_salam",
      importance: {
        score: 88,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 33.22411,
        lng: -8.49621,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/el-jadida/hay-salam",
      "https://mapcarta.com/fr/W322208263",
    ],
    verificationNote: "Yakeey independently certifies Hay Salam as a current El Jadida product neighborhood; OSM-backed Mapcarta names Mosquée Hay Essalam in that local cluster and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_nador_oulad_mimoun_souk_oulad_mimoun",
      type: "landmark",
      citySlug: "nador",
      districtSlug: "oulad-mimoun",
      landmarkSlug: "souk-oulad-mimoun",
      canonicalName: "Souk Oulad Mimoun",
      aliases: ["Zoco Ulad Mimun"],
      category: "retail",
      parentId: "district_nador_oulad_mimoun",
      importance: {
        score: 94,
        tier: "major",
        basis: ["orientation_value", "product_priority", "urban_prominence"],
      },
      visibility: { minZoom: 13.6, retainPriority: true },
      coordinates: {
        lat: 35.1709,
        lng: -2.93614,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/nador/oulad-mimoun",
      "https://mapcarta.com/fr/W319499748",
    ],
    verificationNote: "Yakeey certifies Oulad Mimoun as a current Nador product neighborhood; OSM-backed Mapcarta identifies Souk Oulad Mimoun in Nador and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_temara_massira_1_grands_taxis",
      type: "landmark",
      citySlug: "temara",
      districtSlug: "massira-1",
      landmarkSlug: "station-grands-taxis-massira-1",
      canonicalName: "Station Grands Taxis Massira 1",
      aliases: ["Station Grands Taxis Massira I"],
      category: "transport",
      parentId: "district_temara_massira_1",
      importance: {
        score: 88,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 33.92957,
        lng: -6.90182,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/temara/massira-i",
      "https://mapcarta.com/fr/W1248306544",
    ],
    verificationNote: "Yakeey certifies Massira I as a current Témara product neighborhood; OSM-backed Mapcarta identifies Station Grands Taxis Massira 1 in Témara and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_meknes_zitoune_poste",
      type: "landmark",
      citySlug: "meknes",
      districtSlug: "zitoune",
      landmarkSlug: "meknes-zitoun-poste",
      canonicalName: "Meknes Zitoun",
      aliases: ["Poste Meknes Zitoun", "Meknes Zitoune"],
      category: "civic",
      parentId: "district_meknes_zitoune",
      importance: {
        score: 88,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: {
        lat: 33.86895,
        lng: -5.54706,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/achat/appartement/meknes/zitoune",
      "https://mapcarta.com/fr/N2907762512",
    ],
    verificationNote: "Yakeey independently uses Zitoune as a Meknès product neighborhood; OSM-backed Mapcarta identifies the Barid Al-Maghrib office Meknes Zitoun and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_meknes_marjane_supermarket",
      type: "landmark",
      citySlug: "meknes",
      districtSlug: "marjane",
      landmarkSlug: "marjane-supermarket",
      canonicalName: "Marjane Meknès",
      aliases: ["Marjane"],
      category: "retail",
      parentId: "district_meknes_marjane",
      importance: {
        score: 90,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: {
        lat: 33.90206,
        lng: -5.53684,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/meknes/marjane",
      "https://mapcarta.com/fr/W736832215",
    ],
    verificationNote: "Yakeey certifies Marjane as a current Meknès product neighborhood; OSM-backed Mapcarta identifies the named Marjane supermarket in Meknès and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_casablanca_californie_casablanca_american_school",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "californie",
      landmarkSlug: "casablanca-american-school",
      canonicalName: "Casablanca American School",
      aliases: ["CAS"],
      category: "other",
      parentId: "district_casablanca_californie",
      importance: {
        score: 92,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.7, retainPriority: true },
      coordinates: {
        lat: 33.53687,
        lng: -7.62943,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://www.cas.ac.ma/",
      "https://mapcarta.com/W1364770546",
    ],
    verificationNote: "Casablanca American School gives its address explicitly as Quartier Californie; OSM-backed Mapcarta supplies the verified school point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_sale_tabriquet_gare_sale_tabriquet",
      type: "landmark",
      citySlug: "sale",
      districtSlug: "tabriquet",
      landmarkSlug: "gare-sale-tabriquet",
      canonicalName: "Gare de Salé-Tabriquet",
      aliases: ["Salé-Tabriquet railway station"],
      category: "transport",
      parentId: "district_sale_tabriquet",
      importance: {
        score: 96,
        tier: "flagship",
        basis: ["orientation_value", "product_priority", "urban_prominence"],
      },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: {
        lat: 34.0534,
        lng: -6.8087,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://aurs.org.ma/fr/news/mise-en-ligne-du-plan-damenagement-homologue-de-tabriquet-sale/",
      "https://mapcarta.com/N2622485570",
    ],
    verificationNote: "AURS certifies Tabriquet as a Salé planning sector; OSM-backed Mapcarta explicitly identifies Salé-Tabriquet railway station in the district and supplies the public point context.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_sale_bettana_tram_bettana",
      type: "landmark",
      citySlug: "sale",
      districtSlug: "bettana",
      landmarkSlug: "station-tram-bettana",
      canonicalName: "Station Tram Bettana",
      aliases: ["Bettana Tram Stop"],
      category: "transport",
      parentId: "district_sale_bettana",
      importance: {
        score: 94,
        tier: "major",
        basis: ["orientation_value", "product_priority"],
      },
      visibility: { minZoom: 13.6, retainPriority: true },
      coordinates: {
        lat: 34.035,
        lng: -6.80668,
        precision: "verified_landmark_point",
      },
    },
    sourceRefs: [
      "https://aurs.org.ma/fr/news/lagence-urbaine-de-rabat-sale-met-en-ligne-le-plan-damenagement-homologue-de-bettana/",
      "https://mapcarta.com/fr/N4592889793",
    ],
    verificationNote: "AURS certifies Bettana as a Salé planning sector; OSM-backed Mapcarta identifies the Bettana tram stop and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_temara_hay_al_wifaq_poste",
      type: "landmark",
      citySlug: "temara",
      districtSlug: "hay-al-wifaq",
      landmarkSlug: "temara-al-wifak-poste",
      canonicalName: "Temara Al Wifak",
      aliases: ["Poste Al Wifaq", "Barid Al Maghrib Al Wifak"],
      category: "civic",
      parentId: "district_temara_hay_al_wifaq",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 33.919, lng: -6.935, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/temara",
      "https://mapcarta.com/es/N2907757054",
    ],
    verificationNote: "Yakeey exposes Hay Al Wifaq in the Témara product taxonomy; OSM-backed Mapcarta identifies the Barid Al-Maghrib office Temara Al Wifak and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_temara_ibnou_rochd_lycee",
      type: "landmark",
      citySlug: "temara",
      districtSlug: "ibnou-rochd",
      landmarkSlug: "lycee-ibn-rochd",
      canonicalName: "Lycée Ibn Rochd",
      aliases: ["ثانوية ابن رشد التأهيلية"],
      category: "other",
      parentId: "district_temara_ibnou_rochd",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 33.92534, lng: -6.90065, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/temara",
      "https://mapcarta.com/W435341856",
    ],
    verificationNote: "Yakeey exposes Ibnou Rochd in the Témara product taxonomy; OSM-backed Mapcarta identifies Lycée Ibn Rochd in Témara and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_temara_hay_al_maghreb_al_arabi_ecole",
      type: "landmark",
      citySlug: "temara",
      districtSlug: "hay-al-maghreb-al-arabi",
      landmarkSlug: "ecole-al-maghreb-al-arabi",
      canonicalName: "École Primaire Al Maghrib Al Arabi",
      aliases: ["مدرسة المغرب العربي الابتدائية"],
      category: "other",
      parentId: "district_temara_hay_al_maghreb_al_arabi",
      importance: { score: 88, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: { lat: 33.9324, lng: -6.89396, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/temara",
      "https://mapcarta.com/W435343444",
    ],
    verificationNote: "Yakeey exposes Hay Al Maghreb Al Arabi in the Témara product taxonomy; OSM-backed Mapcarta identifies the namesake primary school in Témara and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_bouznika_hay_riad_poste",
      type: "landmark",
      citySlug: "bouznika",
      districtSlug: "hay-riad",
      landmarkSlug: "bouznika-hay-riad-poste",
      canonicalName: "Bouznika Hay Riad",
      aliases: ["Poste Hay Riad", "Barid Al Maghrib Hay Riad"],
      category: "civic",
      parentId: "district_bouznika_hay_riad",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 33.78004, lng: -7.15855, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/bouznika",
      "https://mapcarta.com/N2907752026",
    ],
    verificationNote: "Yakeey exposes Hay Riad in the Bouznika product taxonomy; OSM-backed Mapcarta identifies the Barid Al-Maghrib office Bouznika Hay Riad and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_meknes_ryad_mosquee_riad",
      type: "landmark",
      citySlug: "meknes",
      districtSlug: "ryad",
      landmarkSlug: "mosquee-riad",
      canonicalName: "Mosquée Riad",
      aliases: ["مسجد الرياض"],
      category: "civic",
      parentId: "district_meknes_ryad",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 33.888, lng: -5.57023, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/meknes",
      "https://mapcarta.com/fr/W327204960",
    ],
    verificationNote: "Yakeey exposes Ryad as a current Meknès product neighborhood; OSM-backed Mapcarta identifies the namesake Mosquée Riad and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_tetouan_ensanche_notre_dame_victoires",
      type: "landmark",
      citySlug: "tetouan",
      districtSlug: "ensanche",
      landmarkSlug: "notre-dame-des-victoires",
      canonicalName: "Église Notre-Dame-des-Victoires",
      aliases: ["Church of Our Lady of Victory", "Iglesia de Nuestra Señora de las Victorias"],
      category: "heritage",
      parentId: "district_tetouan_ensanche",
      importance: { score: 96, tier: "flagship", basis: ["orientation_value", "product_priority", "urban_prominence"] },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: { lat: 35.57004, lng: -5.37508, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://fr.wikipedia.org/wiki/%C3%89glise_Notre-Dame-des-Victoires_de_T%C3%A9touan",
      "https://mapcarta.com/W1207894170",
    ],
    verificationNote: "The church is explicitly described as being in the Ensanche of Tétouan; OSM-backed Mapcarta supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_el_jadida_najd_lycee",
      type: "landmark",
      citySlug: "el-jadida",
      districtSlug: "najd",
      landmarkSlug: "lycee-najd",
      canonicalName: "Lycée Najd",
      aliases: [],
      category: "other",
      parentId: "district_el_jadida_najd",
      importance: { score: 88, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: { lat: 33.22247, lng: -8.50718, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/el-jadida",
      "https://mapcarta.com/W1228540379",
    ],
    verificationNote: "Yakeey exposes Najd as a current El Jadida product neighborhood; OSM-backed Mapcarta identifies Lycée Najd and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_el_jadida_sidi_moussa_ecole",
      type: "landmark",
      citySlug: "el-jadida",
      districtSlug: "sidi-moussa",
      landmarkSlug: "ecole-sidi-moussa",
      canonicalName: "École Sidi Moussa",
      aliases: [],
      category: "other",
      parentId: "district_el_jadida_sidi_moussa",
      importance: { score: 88, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: { lat: 33.23415, lng: -8.49482, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/el-jadida",
      "https://mapcarta.com/W320833378",
    ],
    verificationNote: "Yakeey exposes Sidi Moussa as a current El Jadida product neighborhood; OSM-backed Mapcarta identifies École Sidi Moussa and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_oujda_hay_el_qods_ecole",
      type: "landmark",
      citySlug: "oujda",
      districtSlug: "hay-el-qods",
      landmarkSlug: "ecole-al-qods",
      canonicalName: "École Al Qods",
      aliases: [],
      category: "other",
      parentId: "district_oujda_hay_el_qods",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 34.65606, lng: -1.89364, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/oujda",
      "https://mapcarta.com/W357503007",
    ],
    verificationNote: "Yakeey exposes Hay El Qods in the Oujda product taxonomy; OSM-backed Mapcarta identifies École Al Qods in Oujda and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_oujda_hay_al_massira_lycee",
      type: "landmark",
      citySlug: "oujda",
      districtSlug: "hay-al-massira",
      landmarkSlug: "lycee-al-massira",
      canonicalName: "Lycée Al Massira",
      aliases: [],
      category: "other",
      parentId: "district_oujda_hay_al_massira",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 34.67426, lng: -1.91623, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/oujda",
      "https://mapcarta.com/W290069065",
    ],
    verificationNote: "Yakeey exposes Hay Al Massira in the Oujda product taxonomy; OSM-backed Mapcarta identifies Lycée Al Massira in Oujda and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_oujda_hay_al_andalous_jardin",
      type: "landmark",
      citySlug: "oujda",
      districtSlug: "hay-al-andalous",
      landmarkSlug: "jardin-al-andalouss",
      canonicalName: "Jardin Al Andalouss",
      aliases: ["Jardin Al Andalous"],
      category: "park",
      parentId: "district_oujda_hay_al_andalous",
      importance: { score: 92, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.7, retainPriority: true },
      coordinates: { lat: 34.65676, lng: -1.88488, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/oujda",
      "https://mapcarta.com/W1281328873",
    ],
    verificationNote: "Yakeey exposes Hay Al Andalous in the Oujda product taxonomy; OSM-backed Mapcarta identifies Jardin Al Andalouss in the same Oujda cluster and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_nador_hay_al_matar_clinique",
      type: "landmark",
      citySlug: "nador",
      districtSlug: "hay-al-matar",
      landmarkSlug: "clinique-al-matar",
      canonicalName: "Clinique Al Matar",
      aliases: [],
      category: "hospital",
      parentId: "district_nador_hay_al_matar",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 35.15136, lng: -2.92683, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/nador",
      "https://mapcarta.com/W1093259574",
    ],
    verificationNote: "Yakeey exposes Hay Al Matar in the Nador product taxonomy; OSM-backed Mapcarta identifies Clinique Al Matar in the same local cluster and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_el_jadida_al_boustane_mosquee",
      type: "landmark",
      citySlug: "el-jadida",
      districtSlug: "al-boustane",
      landmarkSlug: "mosquee-el-boustane",
      canonicalName: "Mosquée El Boustane",
      aliases: ["El Boustane"],
      category: "worship",
      parentId: "district_el_jadida_al_boustane",
      importance: { score: 88, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.9, retainPriority: false },
      coordinates: { lat: 33.23194, lng: -8.48379, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/el-jadida",
      "https://mapcarta.com/W1233914038",
    ],
    verificationNote: "Yakeey exposes Al Boustane in the El Jadida product taxonomy; OSM-backed Mapcarta identifies the namesake mosque and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_casablanca_hay_hassani_polyclinique_cnss",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "hay-hassani",
      landmarkSlug: "polyclinique-cnss-hay-hassani",
      canonicalName: "Polyclinique CNSS Hay Hassani",
      aliases: ["مصحة الضمان الإجتماعي الحي الحسني"],
      category: "hospital",
      parentId: "district_casablanca_hay_hassani",
      importance: { score: 94, tier: "major", basis: ["orientation_value", "product_priority", "urban_prominence"] },
      visibility: { minZoom: 13.6, retainPriority: true },
      coordinates: { lat: 33.56699, lng: -7.66859, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://auc.ma/wp-content/uploads/2020/05/pla_compressed.pdf",
      "https://mapcarta.com/W521476354",
    ],
    verificationNote: "AUC certifies Hay Hassani identity; OSM-backed Mapcarta identifies the CNSS polyclinic explicitly as Hay Hassani and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_casablanca_sidi_maarouf_groupe_scolaire",
      type: "landmark",
      citySlug: "casablanca",
      districtSlug: "sidi-maarouf",
      landmarkSlug: "groupe-scolaire-sidi-maarouf",
      canonicalName: "Groupe Scolaire Sidi Maârouf",
      aliases: ["Groupe Scolaire Sidi Maarouf"],
      category: "other",
      parentId: "district_casablanca_sidi_maarouf",
      importance: { score: 92, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.7, retainPriority: true },
      coordinates: { lat: 33.52013, lng: -7.64999, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://auc.ma/wp-content/uploads/2020/05/RAPPORT-JUSTIFICATIF-AINCHOCK.pdf",
      "https://mapcarta.com/fr/N4720321094",
    ],
    verificationNote: "AUC explicitly certifies the Sidi Maârouf identity; OSM-backed Mapcarta identifies Groupe Scolaire Sidi Maârouf and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_sale_hssaine_poste",
      type: "landmark",
      citySlug: "sale",
      districtSlug: "hssaine",
      landmarkSlug: "sale-hssaine-poste",
      canonicalName: "Salé Hssaine",
      aliases: ["Poste Maroc Salé Hssaine"],
      category: "civic",
      parentId: "district_sale_hssaine",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 34.01832, lng: -6.76313, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://aurs.org.ma/fr/news/mise-en-ligne-du-plan-damenagement-homologue-de-hssaine/",
      "https://mapcarta.com/N2907763137",
    ],
    verificationNote: "AURS certifies Hssaine as a Salé planning sector; OSM-backed Mapcarta identifies the Poste Maroc office Salé Hssaine and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_sale_laayayda_poste",
      type: "landmark",
      citySlug: "sale",
      districtSlug: "laayayda",
      landmarkSlug: "sale-layayda-poste",
      canonicalName: "Sale Layayda",
      aliases: ["la poste de Laayayda"],
      category: "civic",
      parentId: "district_sale_laayayda",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 34.06204, lng: -6.7727, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://aurs.org.ma/fr/news/mise-en-ligne-du-plan-damenagement-de-laayayda-sale/",
      "https://mapcarta.com/N2907756732",
    ],
    verificationNote: "AURS certifies Laayayda as a Salé planning sector; OSM-backed Mapcarta identifies the Barid Al-Maghrib office Sale Layayda and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_oujda_hay_boudir_place_boudir",
      type: "landmark",
      citySlug: "oujda",
      districtSlug: "hay-boudir",
      landmarkSlug: "place-boudir",
      canonicalName: "Place Boudir",
      aliases: [],
      category: "park",
      parentId: "district_oujda_hay_boudir",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 34.68812, lng: -1.90712, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/oujda",
      "https://mapcarta.com/W291664329",
    ],
    verificationNote: "Yakeey exposes Hay Boudir in the Oujda product taxonomy; OSM-backed Mapcarta identifies Place Boudir in Oujda and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_oujda_centre_ville_gare",
      type: "landmark",
      citySlug: "oujda",
      districtSlug: "centre-ville",
      landmarkSlug: "gare-d-oujda",
      canonicalName: "Gare d’Oujda",
      aliases: ["Oujda Railway Station"],
      category: "transport",
      parentId: "district_oujda_centre_ville",
      importance: { score: 96, tier: "flagship", basis: ["orientation_value", "product_priority", "urban_prominence"] },
      visibility: { minZoom: 13.5, retainPriority: true },
      coordinates: { lat: 34.68151, lng: -1.92401, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/oujda",
      "https://mapcarta.com/fr/Oujda",
      "https://mapcarta.com/N12173815230",
    ],
    verificationNote: "Yakeey exposes Centre Ville in the Oujda product taxonomy; Mapcarta’s Oujda description explicitly places the railway station in centre-ville and the OSM-backed station page supplies the verified point.",
    verifiedAt: "2026-09-22",
  },

  {
    entity: {
      id: "landmark_el_jadida_plateau_place_perception",
      type: "landmark",
      citySlug: "el-jadida",
      districtSlug: "plateau",
      landmarkSlug: "place-perception-plateau",
      canonicalName: "Place Perception Plateau",
      aliases: [],
      category: "civic",
      parentId: "district_el_jadida_plateau",
      importance: { score: 90, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 13.8, retainPriority: true },
      coordinates: { lat: 33.24769, lng: -8.50947, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/el-jadida",
      "https://mapcarta.com/N12373789242",
    ],
    verificationNote: "Yakeey exposes Plateau as a current El Jadida product neighborhood; OSM-backed Mapcarta identifies Place Perception Plateau by exact toponym and supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_meknes_hamria_pont_hamria",
      type: "landmark",
      citySlug: "meknes",
      districtSlug: "hamria",
      landmarkSlug: "pont-hamria",
      canonicalName: "Pont Hamria",
      aliases: [],
      category: "transport",
      parentId: "district_meknes_hamria",
      importance: { score: 86, tier: "major", basis: ["orientation_value", "product_priority"] },
      visibility: { minZoom: 14.0, retainPriority: false },
      coordinates: { lat: 33.8971, lng: -5.54117, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://yakeey.com/fr-ma/referentiel-de-prix-immobilier/meknes",
      "https://mapcarta.com/N5006127201",
    ],
    verificationNote: "Yakeey exposes Hamria as a current Meknès product neighborhood; the named CityBus stop Pont Hamria is a stable local orientation anchor and OSM-backed Mapcarta supplies the verified point.",
    verifiedAt: "2026-09-22",
  },
  {
    entity: {
      id: "landmark_essaouira_kasbah_sqala",
      type: "landmark",
      citySlug: "essaouira",
      districtSlug: "kasbah",
      landmarkSlug: "sqala-de-la-kasbah",
      canonicalName: "Sqala de la Kasbah",
      aliases: ["Skala de la Kasbah", "Sqala de la Ville"],
      category: "heritage",
      parentId: "district_essaouira_kasbah",
      importance: { score: 99, tier: "flagship", basis: ["orientation_value", "product_priority", "urban_prominence"] },
      visibility: { minZoom: 13.4, retainPriority: true },
      coordinates: { lat: 31.51528, lng: -9.77222, precision: "verified_landmark_point" },
    },
    sourceRefs: [
      "https://visitmarrakech.com/en/listing/the-sqala-of-the-kasbah/",
      "https://whc.unesco.org/fr/list/753",
      "https://wikiuatu.ddns.net/content/wikipedia_fr_all_maxi_2025-06/Sqala_de_la_Kasbah",
    ],
    verificationNote: "The official regional tourism guide explicitly identifies Sqala de la Kasbah in Essaouira and provides its access location; UNESCO certifies the fortified Medina context, while the public heritage record supplies the monument coordinate.",
    verifiedAt: "2026-09-22",
  },
];

const CANONICAL_DISTRICT_IDS = new Set(GEO_NEIGHBORHOODS.map((district) => district.id));

export function getVerifiedLandmarksForDistrict(districtId: string): VerifiedLandmarkEntry[] {
  if (!CANONICAL_DISTRICT_IDS.has(districtId)) return [];
  return VERIFIED_LANDMARKS
    .filter((entry) => entry.entity.parentId === districtId)
    .sort((a, b) => b.entity.importance.score - a.entity.importance.score);
}
