import { applyGeoEnrichment } from "@/lib/listings/apply-geo-enrichment";
import type { Listing } from "@/lib/listings/types";

export const mockListings: Listing[] = [
  {
    id: "casablanca-finance-city-terrasse",
    title: "Appartement lumineux avec terrasse",
    city: "Casablanca",
    neighborhood: "Finance City",
    price: 1250000,
    currency: "DH",
    surface_m2: 85,
    price_per_m2: 14706,
    property_type: "Appartement",
    transaction_type: "buy",
    bedrooms: 2,
    bathrooms: 2,
    freshness_label: "Ajoutée cette semaine",
    source_type: "Source analysée",
    reliability_label: "Informations complètes",
    reliability_score: 88,
    is_mre_friendly: true,
    description:
      "Appartement bien agencé avec terrasse, double exposition et accès rapide aux quartiers d'affaires de Casablanca.",
    image_url: "/images/listings/appartement-casablanca.jpg",
    reliability_explanation:
      "Prix cohérent, données complètes et localisation précise sur une source analysée récente.",
    whatsapp: "+212600000001",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "apartment"
  },
  {
    id: "casablanca-maarif-studio-renove",
    title: "Studio rénové à deux pas du tram",
    city: "Casablanca",
    neighborhood: "Maârif",
    price: 690000,
    currency: "DH",
    surface_m2: 49,
    price_per_m2: 14081,
    property_type: "Studio",
    transaction_type: "buy",
    bedrooms: 1,
    bathrooms: 1,
    freshness_label: "Mis à jour hier",
    source_type: "Agence",
    reliability_label: "Infos limitées",
    reliability_score: 67,
    is_mre_friendly: false,
    description:
      "Studio rénové pour résidence principale ou investissement, proche commerces, tram et bureaux.",
    image_url: "/images/listings/appartement-casablanca.jpg",
    reliability_explanation:
      "Annonce assez complète, mais disponibilité récente non reconfirmée par l'agence.",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "studio"
  },
  {
    // Demo partner listing — promoteur with full image rights
    id: "rabat-hay-riad-neuf-jardin",
    title: "Appartement neuf avec loggia et jardin",
    city: "Rabat",
    neighborhood: "Hay Riad",
    price: 2100000,
    currency: "DH",
    surface_m2: 120,
    price_per_m2: 17500,
    property_type: "Appartement",
    transaction_type: "new",
    bedrooms: 3,
    bathrooms: 2,
    freshness_label: "Projet suivi",
    source_type: "Promoteur",
    reliability_label: "Informations complètes",
    reliability_score: 91,
    is_mre_friendly: true,
    description:
      "Programme neuf avec finitions contemporaines, brochure disponible et livraison annoncée clairement.",
    image_url: "/images/listings/appartement-rabat.jpg",
    reliability_explanation:
      "Données fournies directement par le promoteur avec calendrier et surface confirmés.",
    whatsapp: "+212600000003",
    source_access_level: "partner_full",
    image_permission_status: "allowed",
    image_fallback_type: "new_project",
    main_image_url: "/images/listings/appartement-rabat.jpg",
    image_source: "Partenaire AkarFinder (démo)",
    image_last_checked_at: "2026-06-24"
  },
  {
    id: "rabat-agdal-bureau-location",
    title: "Bureau compact proche gare Agdal",
    city: "Rabat",
    neighborhood: "Agdal",
    price: 11000,
    currency: "DH",
    surface_m2: 72,
    price_per_m2: 153,
    property_type: "Bureau",
    transaction_type: "rent",
    bedrooms: 0,
    bathrooms: 1,
    freshness_label: "Ajoutée il y a 3 jours",
    source_type: "Source analysée",
    reliability_label: "Infos limitées",
    reliability_score: 61,
    is_mre_friendly: false,
    description:
      "Plateau bureau fonctionnel pour activité de service, à quelques minutes de la gare et des grands axes.",
    image_url: "/images/listings/appartement-rabat.jpg",
    reliability_explanation:
      "L'emplacement et le prix sont plausibles, mais des éléments de contact restent à confirmer.",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "bureau"
  },
  {
    id: "tanger-malabata-studio-vue-mer",
    title: "Studio meublé proche corniche",
    city: "Tanger",
    neighborhood: "Malabata",
    price: 650000,
    currency: "DH",
    surface_m2: 45,
    price_per_m2: 14444,
    property_type: "Studio",
    transaction_type: "buy",
    bedrooms: 1,
    bathrooms: 1,
    freshness_label: "Récent",
    source_type: "Source analysée",
    reliability_label: "Informations complètes",
    reliability_score: 84,
    is_mre_friendly: true,
    description:
      "Studio meublé avec potentiel locatif, proche corniche, restaurants et accès portuaire.",
    image_url: "/images/listings/studio-tanger.jpg",
    reliability_explanation:
      "Photos cohérentes, prix aligné sur le quartier et données de surface complètes.",
    whatsapp: "+212600000005",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "studio"
  },
  {
    // Doublon possible — image use forbidden
    id: "marrakech-route-ourika-villa-piscine",
    title: "Villa familiale avec piscine",
    city: "Marrakech",
    neighborhood: "Route de l'Ourika",
    price: 3800000,
    currency: "DH",
    surface_m2: 450,
    price_per_m2: 8444,
    property_type: "Villa",
    transaction_type: "buy",
    bedrooms: 4,
    bathrooms: 3,
    freshness_label: "Cette semaine",
    source_type: "Agence",
    reliability_label: "Doublon possible",
    reliability_score: 46,
    is_mre_friendly: true,
    description:
      "Villa familiale avec piscine, jardin et grand séjour, à distance raisonnable du centre de Marrakech.",
    image_url: "/images/listings/villa-marrakech.jpg",
    reliability_explanation:
      "Prix attractif mais annonce proche d'autres publications similaires, ce qui suggère un doublon potentiel.",
    whatsapp: "+212600000006",
    source_access_level: "indexed_only",
    image_permission_status: "forbidden",
    image_fallback_type: "villa"
  },
  {
    // Demo partner listing — promoteur with full image rights
    id: "agadir-founty-appartement-balcon",
    title: "Appartement récent avec balcon sud",
    city: "Agadir",
    neighborhood: "Founty",
    price: 980000,
    currency: "DH",
    surface_m2: 76,
    price_per_m2: 12895,
    property_type: "Appartement",
    transaction_type: "buy",
    bedrooms: 2,
    bathrooms: 2,
    freshness_label: "Ajoutée aujourd'hui",
    source_type: "Promoteur",
    reliability_label: "Informations complètes",
    reliability_score: 86,
    is_mre_friendly: true,
    description:
      "Appartement moderne à Founty avec balcon, stationnement et accès rapide aux zones balnéaires.",
    image_url: "/images/listings/appartement-rabat.jpg",
    reliability_explanation:
      "Annonce récente avec information complète, unité rattachée à un programme structuré.",
    whatsapp: "+212600000007",
    source_access_level: "partner_full",
    image_permission_status: "allowed",
    image_fallback_type: "apartment",
    main_image_url: "/images/listings/appartement-rabat.jpg",
    image_source: "Partenaire AkarFinder (démo)",
    image_last_checked_at: "2026-06-24"
  },
  {
    id: "fes-ville-nouvelle-appartement-famille",
    title: "Appartement familial proche commerces",
    city: "Fes",
    neighborhood: "Ville Nouvelle",
    price: 840000,
    currency: "DH",
    surface_m2: 98,
    price_per_m2: 8571,
    property_type: "Appartement",
    transaction_type: "buy",
    bedrooms: 3,
    bathrooms: 2,
    freshness_label: "Ajoutée il y a 5 jours",
    source_type: "Source analysée",
    reliability_label: "Infos limitées",
    reliability_score: 58,
    is_mre_friendly: false,
    description:
      "Appartement familial dans un quartier établi, proche commerces, services et écoles.",
    image_url: "/images/listings/appartement-casablanca.jpg",
    reliability_explanation:
      "Annonce exploitable mais détail sur l'étage et disponibilité finale encore manquants.",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "apartment"
  },
  {
    // Photos recyclées — image use forbidden
    id: "kenitra-maamora-maison-jardin",
    title: "Maison avec jardin près de la Maâmora",
    city: "Kenitra",
    neighborhood: "Maâmora",
    price: 1650000,
    currency: "DH",
    surface_m2: 210,
    price_per_m2: 7857,
    property_type: "Maison",
    transaction_type: "buy",
    bedrooms: 4,
    bathrooms: 3,
    freshness_label: "Ajoutée cette semaine",
    source_type: "Agence",
    reliability_label: "Infos limitées",
    reliability_score: 64,
    is_mre_friendly: true,
    description:
      "Maison familiale avec jardin et stationnement, dans un secteur recherché pour les familles.",
    image_url: "/images/listings/villa-marrakech.jpg",
    reliability_explanation:
      "Bien détaillé avec plusieurs atouts, mais une partie des photos semble recyclée d'une annonce plus ancienne.",
    whatsapp: "+212600000009",
    source_access_level: "indexed_only",
    image_permission_status: "forbidden",
    image_fallback_type: "generic"
  },
  {
    id: "mohammedia-parc-appartement-moderne",
    title: "Appartement moderne proche parc",
    city: "Mohammedia",
    neighborhood: "Parc",
    price: 1120000,
    currency: "DH",
    surface_m2: 88,
    price_per_m2: 12727,
    property_type: "Appartement",
    transaction_type: "buy",
    bedrooms: 2,
    bathrooms: 2,
    freshness_label: "Mis à jour cette semaine",
    source_type: "Source analysée",
    reliability_label: "Informations complètes",
    reliability_score: 82,
    is_mre_friendly: false,
    description:
      "Appartement bien distribué, proche parc et axes principaux, adapté à une vie de quartier calme.",
    image_url: "/images/listings/appartement-casablanca.jpg",
    reliability_explanation:
      "Cohérence prix/surface solide et contenu suffisamment complet pour une lecture fiable.",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "apartment"
  },
  {
    // V9.5 dev fixture — validates source badge rendering for public_index_source
    id: "casablanca-v95-mubawab-fixture",
    title: "Appartement 3 pièces, Ain Diab",
    city: "Casablanca",
    neighborhood: "Ain Diab",
    price: 1350000,
    currency: "DH",
    surface_m2: 90,
    price_per_m2: 15000,
    property_type: "Appartement",
    transaction_type: "buy",
    bedrooms: 2,
    bathrooms: 1,
    freshness_label: "Indexé il y a 2 jours",
    source_type: "Source analysée",
    reliability_label: "Infos limitées",
    reliability_score: 62,
    is_mre_friendly: false,
    description: "Appartement indexé depuis une source publique — informations à confirmer directement sur le site original.",
    image_url: "",
    reliability_explanation: "Source publique indexée — aperçu limité, données à confirmer.",
    source_name: "Mubawab",
    listing_url: "https://www.mubawab.ma",
    source_access_level: "indexed_only",
    image_permission_status: "unknown",
    image_fallback_type: "apartment",
    // V9.5 display policy fields
    source_display_type: "public_index_source",
    source_badge: "public_indexed",
    display_depth: "limited_preview",
    original_source_required: true,
    allowed_ctas: ["view_original", "view_source", "compare"],
    source_attribution_label: "Source publique indexée",
    display_policy_reason: "Source publique indexée — aperçu limité, redirection vers le site original.",
  },
  {
    // Doublon possible — image use forbidden
    id: "casablanca-bouskoura-terrain-residentiel",
    title: "Terrain résidentiel à vendre",
    city: "Casablanca",
    neighborhood: "Bouskoura",
    price: 1500000,
    currency: "DH",
    surface_m2: 600,
    price_per_m2: 2500,
    property_type: "Terrain",
    transaction_type: "buy",
    bedrooms: 0,
    bathrooms: 0,
    freshness_label: "À confirmer",
    source_type: "Source analysée",
    reliability_label: "Doublon possible",
    reliability_score: 42,
    is_mre_friendly: false,
    description:
      "Terrain résidentiel pour projet privé, dans une zone prisée de Bouskoura.",
    image_url: "/images/listings/terrain-bouskoura.jpg",
    reliability_explanation:
      "Le prix au m² est plausible, mais plusieurs annonces similaires circulent sans preuve de disponibilité unique.",
    source_access_level: "indexed_only",
    image_permission_status: "forbidden",
    image_fallback_type: "terrain"
  }
];

// P10A — exported enriched mocks (geo fields resolved from centroids).
// These are the listings consumers should use when they want geo-aware data.
export const geoEnrichedMockListings: Listing[] = applyGeoEnrichment(mockListings);
