import type { PartnerListingStandard } from "./partner-listing-types";

const FICTIONAL_UPDATE_DATE = "2026-07-04T09:00:00.000Z";

export const FICTIONAL_PROMOTER_DEMO_CASABLANCA_PROJECT: PartnerListingStandard = {
  partner_id: "demo-promoter-casablanca",
  partner_type: "promoter",
  partner_tier: "promoter_partner",
  authorization_status: "partner_authorized",
  source_authorization_note: "Exemple fictif pour documentation produit AkarFinder.",
  transaction_type: "new",
  property_type: "project",
  city: "Casablanca",
  district: "Racine",
  location_level: "approximate_zone",
  approximate_area_label: "Secteur Racine, Casablanca",
  address_public_allowed: false,
  price_range_min: 1800000,
  price_range_max: 3200000,
  currency: "MAD",
  price_display_mode: "range",
  surface_m2: 92,
  bedrooms: 2,
  bathrooms: 2,
  parking: true,
  terrace: true,
  condition: "new",
  availability_status: "upcoming",
  last_partner_update_at: FICTIONAL_UPDATE_DATE,
  photos_authorized: true,
  photo_count: 8,
  media_usage_scope: "akarfinder_partner_page",
  contact_authorized: true,
  contact_mode: "partner_page",
  title: "Projet Demo Casablanca",
  short_description: "Exemple fictif de projet neuf structure pour une page partenaire.",
  normalized_description: "Projet demo a Casablanca avec localisation approximative autorisee.",
  highlights: ["Quartier renseigne", "Fourchette de prix", "Photos autorisees"],
  points_to_verify: ["Disponibilite exacte", "Plan final", "Charges"],
  proximity_allowed: true,
  neighborhood_context_allowed: true,
  mobility_context_allowed: true,
  floor_plan_authorized: true,
  floor_plan_available: true,
  floor_plan_type: "unit_floor_plan",
  floor_plan_display_mode: "visible_on_partner_page",
  floor_plan_source: "partner_provided",
  floor_plan_scope: "unit",
  floor_plan_has_dimensions: true,
  floor_plan_has_room_labels: true,
  floor_plan_has_orientation: true,
  floor_plan_has_surface_breakdown: true,
  floor_plan_usage_note: "Plan 2D fictif fourni par le partenaire demo.",
};

export const FICTIONAL_AGENCY_DEMO_RABAT_APARTMENT: PartnerListingStandard = {
  partner_id: "demo-agency-rabat",
  partner_type: "agency",
  partner_tier: "agency_premium",
  authorization_status: "partner_authorized",
  source_authorization_note: "Exemple fictif pour documentation produit AkarFinder.",
  transaction_type: "rent",
  property_type: "apartment",
  city: "Rabat",
  district: "Agdal",
  location_level: "district_only",
  approximate_area_label: "Quartier Agdal, Rabat",
  address_public_allowed: false,
  price_amount: 8500,
  currency: "MAD",
  price_display_mode: "exact",
  surface_m2: 78,
  bedrooms: 2,
  bathrooms: 1,
  floor: 3,
  elevator: true,
  parking: false,
  furnished: true,
  availability_status: "available",
  last_partner_update_at: FICTIONAL_UPDATE_DATE,
  photos_authorized: true,
  photo_count: 6,
  media_usage_scope: "akarfinder_partner_page",
  contact_authorized: true,
  contact_mode: "form",
  title: "Appartement Demo Rabat",
  short_description: "Exemple fictif d'appartement agence avec fiche structuree.",
  normalized_description: "Appartement demo a Rabat Agdal, donnees fictives et autorisees.",
  highlights: ["Surface renseignee", "Contact autorise", "Photos autorisees"],
  points_to_verify: ["Etat des meubles", "Conditions de bail"],
  proximity_allowed: true,
  neighborhood_context_allowed: true,
  mobility_context_allowed: false,
  floor_plan_authorized: true,
  floor_plan_available: true,
  floor_plan_type: "unit_floor_plan",
  floor_plan_display_mode: "available_on_request",
  floor_plan_source: "partner_provided",
  floor_plan_scope: "unit",
  floor_plan_has_dimensions: true,
  floor_plan_has_room_labels: true,
  floor_plan_has_orientation: false,
  floor_plan_has_surface_breakdown: true,
  floor_plan_usage_note: "Plan optionnel fictif disponible sur demande partenaire.",
};

export const FICTIONAL_PROMOTER_DEMO_WITHOUT_FLOOR_PLAN: PartnerListingStandard = {
  ...FICTIONAL_PROMOTER_DEMO_CASABLANCA_PROJECT,
  partner_id: "demo-promoter-without-floor-plan",
  title: "Projet Demo Sans Plan 2D",
  floor_plan_authorized: false,
  floor_plan_available: false,
  floor_plan_type: "none",
  floor_plan_display_mode: "hidden",
  floor_plan_source: "demo_placeholder",
  floor_plan_scope: "unknown",
  floor_plan_has_dimensions: false,
  floor_plan_has_room_labels: false,
  floor_plan_has_orientation: false,
  floor_plan_has_surface_breakdown: false,
  floor_plan_usage_note: "Aucun plan 2D autorise dans cet exemple fictif.",
};

export const FICTIONAL_AGENCY_DEMO_WITHOUT_FLOOR_PLAN: PartnerListingStandard = {
  ...FICTIONAL_AGENCY_DEMO_RABAT_APARTMENT,
  partner_id: "demo-agency-without-floor-plan",
  title: "Agence Demo Sans Plan 2D",
  mobility_context_allowed: true,
  floor_plan_authorized: false,
  floor_plan_available: false,
  floor_plan_type: "none",
  floor_plan_display_mode: "hidden",
  floor_plan_source: "demo_placeholder",
  floor_plan_scope: "unknown",
  floor_plan_has_dimensions: false,
  floor_plan_has_room_labels: false,
  floor_plan_has_orientation: false,
  floor_plan_has_surface_breakdown: false,
  floor_plan_usage_note: "Plan 2D absent dans cet exemple agence fictif.",
};
